[workspace]
members = [
    "api",
    "haste",
    "haste/crates/*",
    "live-events",
    "tools/active-matches-scraper",
    "tools/builds-fetcher",
    "tools/common",
    "tools/demo-analyzer",
    "tools/history-fetcher",
    "tools/hltv-scraper",
    "tools/ingest-worker",
    "tools/matchdata-downloader",
    "tools/salt-scraper",
    "tools/steam-profile-fetcher",
    "tools/update-assets-tables",
    "valveprotos",
]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
# Shared in-repo crates
common = { version = "0.1.0", path = "tools/common" }
valveprotos = { path = "valveprotos" }
haste = { path = "haste", features = ["async"] }
haste_broadcast = { path = "haste/crates/haste_broadcast" }
haste_core = { path = "haste/crates/haste_core" }
haste_vartype = { path = "haste/crates/haste_vartype" }
dungers = { path = "haste/crates/dungers" }
dungers_bitbuf = { path = "haste/crates/dungers_bitbuf" }
dungers_charsor = { path = "haste/crates/dungers_charsor" }
dungers_varint = { path = "haste/crates/dungers_varint" }

anyhow = "1.0.104"
async-compression = "0.4.48"
base64 = "0.23.1"
cached = "4.0"
clap = { version = "4.6.7", features = ["derive", "env"] }
clickhouse = { version = "0.15.2", features = ["zstd"] }
fred = { version = "10.1.0", features = ["i-hexpire"] }
futures = "0.3.34"
itertools = "0.15.0"
metrics = "0.24.6"
object_store = { version = "0.14.2", features = ["aws"] }
opentelemetry = { version = "0.32", features = ["logs", "trace"] }
opentelemetry_sdk = { version = "0.32", features = ["logs", "trace"] }
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic", "logs", "trace"] }
opentelemetry-appender-tracing = { version = "0.32", features = ["experimental_metadata_attributes"] }
prost = "0.14.4"
rand = "0.10.2"
reqwest = "0.13.5"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_repr = "0.1.21"
sqlx = "0.9.0"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
tokio-util = "0.7.19"
tracing = "0.1.44"
tracing-opentelemetry = "0.33"
tryhard = "0.5.2"

# haste, dungers
bytemuck = "1.23.1"
bytes = "1.11.1"
dyn-clone = "1.0.20"
expect-test = "1.5.1"
hashbrown = { version = "0.16.1", default-features = false }
http = "1.4.0"
log = "0.4.29"
nohash = "0.2.0"
snap = "1.1.1"
sync-unsafe-cell = "0.1.1"

[profile.dev]
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.dev.package."*"]
debug = false

[profile.test.package.libduckdb-sys]
opt-level = 3
[profile.test.package.clickhouse-sql-parser]
opt-level = 3
[profile.test.package.antlr4rust]
opt-level = 3
