/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbilitiesRouteImport } from './routes/abilities'
import { Route as BadgeDistributionRouteImport } from './routes/badge-distribution'
import { Route as DataDumpsRouteImport } from './routes/data-dumps'
import { Route as DataPrivacyRouteImport } from './routes/data-privacy'
import { Route as DeadlockdleRouteImport } from './routes/deadlockdle'
import { Route as DeadlockstatsPrivacyRouteImport } from './routes/deadlockstats-privacy'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as GamesRouteImport } from './routes/games'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as IngestCacheRouteImport } from './routes/ingest-cache'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PatronRouteImport } from './routes/patron'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Sitemap_indexDotxmlRouteImport } from './routes/sitemap_index[.]xml'
import { Route as TeamBuilderRouteImport } from './routes/team-builder'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as AnalyticsAbilitiesRouteImport } from './routes/analytics.abilities'
import { Route as AnalyticsGamesRouteImport } from './routes/analytics.games'
import { Route as AnalyticsHeroesRouteImport } from './routes/analytics.heroes'
import { Route as AnalyticsItemsRouteImport } from './routes/analytics.items'
import { Route as AnalyticsPlayersRouteImport } from './routes/analytics.players'
import { Route as AnalyticsTeamBuilderRouteImport } from './routes/analytics.team-builder'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityBadgeDistributionRouteImport } from './routes/community.badge-distribution'
import { Route as CommunityHeatmapRouteImport } from './routes/community.heatmap'
import { Route as CommunityLeaderboardRouteImport } from './routes/community.leaderboard'
import { Route as DeadlockdleIndexRouteImport } from './routes/deadlockdle/index'
import { Route as DeadlockdleGuessAbilityRouteImport } from './routes/deadlockdle/guess-ability'
import { Route as DeadlockdleGuessHeroRouteImport } from './routes/deadlockdle/guess-hero'
import { Route as DeadlockdleGuessItemRouteImport } from './routes/deadlockdle/guess-item'
import { Route as DeadlockdleGuessSoundRouteImport } from './routes/deadlockdle/guess-sound'
import { Route as DeadlockdleItemStatsRouteImport } from './routes/deadlockdle/item-stats'
import { Route as DeadlockdleTriviaRouteImport } from './routes/deadlockdle/trivia'
import { Route as FlashcardsIndexRouteImport } from './routes/flashcards/index'
import { Route as FlashcardsHeroesRouteImport } from './routes/flashcards/heroes'
import { Route as FlashcardsItemEffectsRouteImport } from './routes/flashcards/item-effects'
import { Route as FlashcardsItemUpgradesRouteImport } from './routes/flashcards/item-upgrades'
import { Route as FlashcardsItemsRouteImport } from './routes/flashcards/items'
import { Route as HeroesIndexRouteImport } from './routes/heroes.index'
import { Route as HeroesHeroNameRouteImport } from './routes/heroes.$heroName'
import { Route as ItemsIndexRouteImport } from './routes/items.index'
import { Route as ItemsItemNameRouteImport } from './routes/items.$itemName'
import { Route as PlayersAccountIdRouteImport } from './routes/players_.$accountId'
import { Route as StreamkitIndexRouteImport } from './routes/streamkit/index'
import { Route as AnalyticsHeroesIndexRouteImport } from './routes/analytics.heroes.index'
import { Route as AnalyticsHeroesHeroNameRouteImport } from './routes/analytics.heroes.$heroName'
import { Route as AnalyticsItemsIndexRouteImport } from './routes/analytics.items.index'
import { Route as AnalyticsItemsItemNameRouteImport } from './routes/analytics.items.$itemName'
import { Route as AuthPatreonCallbackRouteImport } from './routes/auth/patreon/callback'
import { Route as StreamkitWidgetsRegionAccountIdWidgetTypeRouteImport } from './routes/streamkit/widgets/$region/$accountId/$widgetType'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbilitiesRoute = AbilitiesRouteImport.update({
  id: '/abilities',
  path: '/abilities',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeDistributionRoute = BadgeDistributionRouteImport.update({
  id: '/badge-distribution',
  path: '/badge-distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDumpsRoute = DataDumpsRouteImport.update({
  id: '/data-dumps',
  path: '/data-dumps',
  getParentRoute: () => rootRouteImport,
} as any)
const DataPrivacyRoute = DataPrivacyRouteImport.update({
  id: '/data-privacy',
  path: '/data-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlockdleRoute = DeadlockdleRouteImport.update({
  id: '/deadlockdle',
  path: '/deadlockdle',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlockstatsPrivacyRoute = DeadlockstatsPrivacyRouteImport.update({
  id: '/deadlockstats-privacy',
  path: '/deadlockstats-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestCacheRoute = IngestCacheRouteImport.update({
  id: '/ingest-cache',
  path: '/ingest-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatronRoute = PatronRouteImport.update({
  id: '/patron',
  path: '/patron',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Sitemap_indexDotxmlRoute = Sitemap_indexDotxmlRouteImport.update({
  id: '/sitemap_index.xml',
  path: '/sitemap_index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamBuilderRoute = TeamBuilderRouteImport.update({
  id: '/team-builder',
  path: '/team-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsAbilitiesRoute = AnalyticsAbilitiesRouteImport.update({
  id: '/analytics/abilities',
  path: '/analytics/abilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsGamesRoute = AnalyticsGamesRouteImport.update({
  id: '/analytics/games',
  path: '/analytics/games',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsHeroesRoute = AnalyticsHeroesRouteImport.update({
  id: '/analytics/heroes',
  path: '/analytics/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsItemsRoute = AnalyticsItemsRouteImport.update({
  id: '/analytics/items',
  path: '/analytics/items',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsPlayersRoute = AnalyticsPlayersRouteImport.update({
  id: '/analytics/players',
  path: '/analytics/players',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsTeamBuilderRoute = AnalyticsTeamBuilderRouteImport.update({
  id: '/analytics/team-builder',
  path: '/analytics/team-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityBadgeDistributionRoute =
  CommunityBadgeDistributionRouteImport.update({
    id: '/community/badge-distribution',
    path: '/community/badge-distribution',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunityHeatmapRoute = CommunityHeatmapRouteImport.update({
  id: '/community/heatmap',
  path: '/community/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityLeaderboardRoute = CommunityLeaderboardRouteImport.update({
  id: '/community/leaderboard',
  path: '/community/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlockdleIndexRoute = DeadlockdleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleGuessAbilityRoute = DeadlockdleGuessAbilityRouteImport.update({
  id: '/guess-ability',
  path: '/guess-ability',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleGuessHeroRoute = DeadlockdleGuessHeroRouteImport.update({
  id: '/guess-hero',
  path: '/guess-hero',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleGuessItemRoute = DeadlockdleGuessItemRouteImport.update({
  id: '/guess-item',
  path: '/guess-item',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleGuessSoundRoute = DeadlockdleGuessSoundRouteImport.update({
  id: '/guess-sound',
  path: '/guess-sound',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleItemStatsRoute = DeadlockdleItemStatsRouteImport.update({
  id: '/item-stats',
  path: '/item-stats',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleTriviaRoute = DeadlockdleTriviaRouteImport.update({
  id: '/trivia',
  path: '/trivia',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const FlashcardsIndexRoute = FlashcardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FlashcardsRoute,
} as any)
const FlashcardsHeroesRoute = FlashcardsHeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => FlashcardsRoute,
} as any)
const FlashcardsItemEffectsRoute = FlashcardsItemEffectsRouteImport.update({
  id: '/item-effects',
  path: '/item-effects',
  getParentRoute: () => FlashcardsRoute,
} as any)
const FlashcardsItemUpgradesRoute = FlashcardsItemUpgradesRouteImport.update({
  id: '/item-upgrades',
  path: '/item-upgrades',
  getParentRoute: () => FlashcardsRoute,
} as any)
const FlashcardsItemsRoute = FlashcardsItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => FlashcardsRoute,
} as any)
const HeroesIndexRoute = HeroesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeroesRoute,
} as any)
const HeroesHeroNameRoute = HeroesHeroNameRouteImport.update({
  id: '/$heroName',
  path: '/$heroName',
  getParentRoute: () => HeroesRoute,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsItemNameRoute = ItemsItemNameRouteImport.update({
  id: '/$itemName',
  path: '/$itemName',
  getParentRoute: () => ItemsRoute,
} as any)
const PlayersAccountIdRoute = PlayersAccountIdRouteImport.update({
  id: '/players_/$accountId',
  path: '/players/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamkitIndexRoute = StreamkitIndexRouteImport.update({
  id: '/streamkit/',
  path: '/streamkit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsHeroesIndexRoute = AnalyticsHeroesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsHeroesRoute,
} as any)
const AnalyticsHeroesHeroNameRoute = AnalyticsHeroesHeroNameRouteImport.update({
  id: '/$heroName',
  path: '/$heroName',
  getParentRoute: () => AnalyticsHeroesRoute,
} as any)
const AnalyticsItemsIndexRoute = AnalyticsItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsItemsRoute,
} as any)
const AnalyticsItemsItemNameRoute = AnalyticsItemsItemNameRouteImport.update({
  id: '/$itemName',
  path: '/$itemName',
  getParentRoute: () => AnalyticsItemsRoute,
} as any)
const AuthPatreonCallbackRoute = AuthPatreonCallbackRouteImport.update({
  id: '/auth/patreon/callback',
  path: '/auth/patreon/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamkitWidgetsRegionAccountIdWidgetTypeRoute =
  StreamkitWidgetsRegionAccountIdWidgetTypeRouteImport.update({
    id: '/streamkit/widgets/$region/$accountId/$widgetType',
    path: '/streamkit/widgets/$region/$accountId/$widgetType',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abilities': typeof AbilitiesRoute
  '/badge-distribution': typeof BadgeDistributionRoute
  '/data-dumps': typeof DataDumpsRoute
  '/data-privacy': typeof DataPrivacyRoute
  '/deadlockdle': typeof DeadlockdleRouteWithChildren
  '/deadlockstats-privacy': typeof DeadlockstatsPrivacyRoute
  '/flashcards': typeof FlashcardsRouteWithChildren
  '/games': typeof GamesRoute
  '/heatmap': typeof HeatmapRoute
  '/heroes': typeof HeroesRouteWithChildren
  '/ingest-cache': typeof IngestCacheRoute
  '/items': typeof ItemsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/patron': typeof PatronRoute
  '/players': typeof PlayersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/team-builder': typeof TeamBuilderRoute
  '/tracker': typeof TrackerRoute
  '/analytics/abilities': typeof AnalyticsAbilitiesRoute
  '/analytics/games': typeof AnalyticsGamesRoute
  '/analytics/heroes': typeof AnalyticsHeroesRouteWithChildren
  '/analytics/items': typeof AnalyticsItemsRouteWithChildren
  '/analytics/players': typeof AnalyticsPlayersRoute
  '/analytics/team-builder': typeof AnalyticsTeamBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/badge-distribution': typeof CommunityBadgeDistributionRoute
  '/community/heatmap': typeof CommunityHeatmapRoute
  '/community/leaderboard': typeof CommunityLeaderboardRoute
  '/deadlockdle/guess-ability': typeof DeadlockdleGuessAbilityRoute
  '/deadlockdle/guess-hero': typeof DeadlockdleGuessHeroRoute
  '/deadlockdle/guess-item': typeof DeadlockdleGuessItemRoute
  '/deadlockdle/guess-sound': typeof DeadlockdleGuessSoundRoute
  '/deadlockdle/item-stats': typeof DeadlockdleItemStatsRoute
  '/deadlockdle/trivia': typeof DeadlockdleTriviaRoute
  '/flashcards/heroes': typeof FlashcardsHeroesRoute
  '/flashcards/item-effects': typeof FlashcardsItemEffectsRoute
  '/flashcards/item-upgrades': typeof FlashcardsItemUpgradesRoute
  '/flashcards/items': typeof FlashcardsItemsRoute
  '/heroes/$heroName': typeof HeroesHeroNameRoute
  '/items/$itemName': typeof ItemsItemNameRoute
  '/players/$accountId': typeof PlayersAccountIdRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/deadlockdle/': typeof DeadlockdleIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/heroes/': typeof HeroesIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/streamkit/': typeof StreamkitIndexRoute
  '/analytics/heroes/$heroName': typeof AnalyticsHeroesHeroNameRoute
  '/analytics/items/$itemName': typeof AnalyticsItemsItemNameRoute
  '/auth/patreon/callback': typeof AuthPatreonCallbackRoute
  '/analytics/heroes/': typeof AnalyticsHeroesIndexRoute
  '/analytics/items/': typeof AnalyticsItemsIndexRoute
  '/streamkit/widgets/$region/$accountId/$widgetType': typeof StreamkitWidgetsRegionAccountIdWidgetTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abilities': typeof AbilitiesRoute
  '/badge-distribution': typeof BadgeDistributionRoute
  '/data-dumps': typeof DataDumpsRoute
  '/data-privacy': typeof DataPrivacyRoute
  '/deadlockstats-privacy': typeof DeadlockstatsPrivacyRoute
  '/games': typeof GamesRoute
  '/heatmap': typeof HeatmapRoute
  '/ingest-cache': typeof IngestCacheRoute
  '/leaderboard': typeof LeaderboardRoute
  '/patron': typeof PatronRoute
  '/players': typeof PlayersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/team-builder': typeof TeamBuilderRoute
  '/tracker': typeof TrackerRoute
  '/analytics/abilities': typeof AnalyticsAbilitiesRoute
  '/analytics/games': typeof AnalyticsGamesRoute
  '/analytics/players': typeof AnalyticsPlayersRoute
  '/analytics/team-builder': typeof AnalyticsTeamBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/badge-distribution': typeof CommunityBadgeDistributionRoute
  '/community/heatmap': typeof CommunityHeatmapRoute
  '/community/leaderboard': typeof CommunityLeaderboardRoute
  '/deadlockdle/guess-ability': typeof DeadlockdleGuessAbilityRoute
  '/deadlockdle/guess-hero': typeof DeadlockdleGuessHeroRoute
  '/deadlockdle/guess-item': typeof DeadlockdleGuessItemRoute
  '/deadlockdle/guess-sound': typeof DeadlockdleGuessSoundRoute
  '/deadlockdle/item-stats': typeof DeadlockdleItemStatsRoute
  '/deadlockdle/trivia': typeof DeadlockdleTriviaRoute
  '/flashcards/heroes': typeof FlashcardsHeroesRoute
  '/flashcards/item-effects': typeof FlashcardsItemEffectsRoute
  '/flashcards/item-upgrades': typeof FlashcardsItemUpgradesRoute
  '/flashcards/items': typeof FlashcardsItemsRoute
  '/heroes/$heroName': typeof HeroesHeroNameRoute
  '/items/$itemName': typeof ItemsItemNameRoute
  '/players/$accountId': typeof PlayersAccountIdRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/community': typeof CommunityIndexRoute
  '/deadlockdle': typeof DeadlockdleIndexRoute
  '/flashcards': typeof FlashcardsIndexRoute
  '/heroes': typeof HeroesIndexRoute
  '/items': typeof ItemsIndexRoute
  '/streamkit': typeof StreamkitIndexRoute
  '/analytics/heroes/$heroName': typeof AnalyticsHeroesHeroNameRoute
  '/analytics/items/$itemName': typeof AnalyticsItemsItemNameRoute
  '/auth/patreon/callback': typeof AuthPatreonCallbackRoute
  '/analytics/heroes': typeof AnalyticsHeroesIndexRoute
  '/analytics/items': typeof AnalyticsItemsIndexRoute
  '/streamkit/widgets/$region/$accountId/$widgetType': typeof StreamkitWidgetsRegionAccountIdWidgetTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abilities': typeof AbilitiesRoute
  '/badge-distribution': typeof BadgeDistributionRoute
  '/data-dumps': typeof DataDumpsRoute
  '/data-privacy': typeof DataPrivacyRoute
  '/deadlockdle': typeof DeadlockdleRouteWithChildren
  '/deadlockstats-privacy': typeof DeadlockstatsPrivacyRoute
  '/flashcards': typeof FlashcardsRouteWithChildren
  '/games': typeof GamesRoute
  '/heatmap': typeof HeatmapRoute
  '/heroes': typeof HeroesRouteWithChildren
  '/ingest-cache': typeof IngestCacheRoute
  '/items': typeof ItemsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/patron': typeof PatronRoute
  '/players': typeof PlayersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/team-builder': typeof TeamBuilderRoute
  '/tracker': typeof TrackerRoute
  '/analytics/abilities': typeof AnalyticsAbilitiesRoute
  '/analytics/games': typeof AnalyticsGamesRoute
  '/analytics/heroes': typeof AnalyticsHeroesRouteWithChildren
  '/analytics/items': typeof AnalyticsItemsRouteWithChildren
  '/analytics/players': typeof AnalyticsPlayersRoute
  '/analytics/team-builder': typeof AnalyticsTeamBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/badge-distribution': typeof CommunityBadgeDistributionRoute
  '/community/heatmap': typeof CommunityHeatmapRoute
  '/community/leaderboard': typeof CommunityLeaderboardRoute
  '/deadlockdle/guess-ability': typeof DeadlockdleGuessAbilityRoute
  '/deadlockdle/guess-hero': typeof DeadlockdleGuessHeroRoute
  '/deadlockdle/guess-item': typeof DeadlockdleGuessItemRoute
  '/deadlockdle/guess-sound': typeof DeadlockdleGuessSoundRoute
  '/deadlockdle/item-stats': typeof DeadlockdleItemStatsRoute
  '/deadlockdle/trivia': typeof DeadlockdleTriviaRoute
  '/flashcards/heroes': typeof FlashcardsHeroesRoute
  '/flashcards/item-effects': typeof FlashcardsItemEffectsRoute
  '/flashcards/item-upgrades': typeof FlashcardsItemUpgradesRoute
  '/flashcards/items': typeof FlashcardsItemsRoute
  '/heroes/$heroName': typeof HeroesHeroNameRoute
  '/items/$itemName': typeof ItemsItemNameRoute
  '/players_/$accountId': typeof PlayersAccountIdRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/deadlockdle/': typeof DeadlockdleIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/heroes/': typeof HeroesIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/streamkit/': typeof StreamkitIndexRoute
  '/analytics/heroes/$heroName': typeof AnalyticsHeroesHeroNameRoute
  '/analytics/items/$itemName': typeof AnalyticsItemsItemNameRoute
  '/auth/patreon/callback': typeof AuthPatreonCallbackRoute
  '/analytics/heroes/': typeof AnalyticsHeroesIndexRoute
  '/analytics/items/': typeof AnalyticsItemsIndexRoute
  '/streamkit/widgets/$region/$accountId/$widgetType': typeof StreamkitWidgetsRegionAccountIdWidgetTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abilities'
    | '/badge-distribution'
    | '/data-dumps'
    | '/data-privacy'
    | '/deadlockdle'
    | '/deadlockstats-privacy'
    | '/flashcards'
    | '/games'
    | '/heatmap'
    | '/heroes'
    | '/ingest-cache'
    | '/items'
    | '/leaderboard'
    | '/patron'
    | '/players'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/team-builder'
    | '/tracker'
    | '/analytics/abilities'
    | '/analytics/games'
    | '/analytics/heroes'
    | '/analytics/items'
    | '/analytics/players'
    | '/analytics/team-builder'
    | '/blog/$slug'
    | '/community/badge-distribution'
    | '/community/heatmap'
    | '/community/leaderboard'
    | '/deadlockdle/guess-ability'
    | '/deadlockdle/guess-hero'
    | '/deadlockdle/guess-item'
    | '/deadlockdle/guess-sound'
    | '/deadlockdle/item-stats'
    | '/deadlockdle/trivia'
    | '/flashcards/heroes'
    | '/flashcards/item-effects'
    | '/flashcards/item-upgrades'
    | '/flashcards/items'
    | '/heroes/$heroName'
    | '/items/$itemName'
    | '/players/$accountId'
    | '/analytics/'
    | '/blog/'
    | '/community/'
    | '/deadlockdle/'
    | '/flashcards/'
    | '/heroes/'
    | '/items/'
    | '/streamkit/'
    | '/analytics/heroes/$heroName'
    | '/analytics/items/$itemName'
    | '/auth/patreon/callback'
    | '/analytics/heroes/'
    | '/analytics/items/'
    | '/streamkit/widgets/$region/$accountId/$widgetType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abilities'
    | '/badge-distribution'
    | '/data-dumps'
    | '/data-privacy'
    | '/deadlockstats-privacy'
    | '/games'
    | '/heatmap'
    | '/ingest-cache'
    | '/leaderboard'
    | '/patron'
    | '/players'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/team-builder'
    | '/tracker'
    | '/analytics/abilities'
    | '/analytics/games'
    | '/analytics/players'
    | '/analytics/team-builder'
    | '/blog/$slug'
    | '/community/badge-distribution'
    | '/community/heatmap'
    | '/community/leaderboard'
    | '/deadlockdle/guess-ability'
    | '/deadlockdle/guess-hero'
    | '/deadlockdle/guess-item'
    | '/deadlockdle/guess-sound'
    | '/deadlockdle/item-stats'
    | '/deadlockdle/trivia'
    | '/flashcards/heroes'
    | '/flashcards/item-effects'
    | '/flashcards/item-upgrades'
    | '/flashcards/items'
    | '/heroes/$heroName'
    | '/items/$itemName'
    | '/players/$accountId'
    | '/analytics'
    | '/blog'
    | '/community'
    | '/deadlockdle'
    | '/flashcards'
    | '/heroes'
    | '/items'
    | '/streamkit'
    | '/analytics/heroes/$heroName'
    | '/analytics/items/$itemName'
    | '/auth/patreon/callback'
    | '/analytics/heroes'
    | '/analytics/items'
    | '/streamkit/widgets/$region/$accountId/$widgetType'
  id:
    | '__root__'
    | '/'
    | '/abilities'
    | '/badge-distribution'
    | '/data-dumps'
    | '/data-privacy'
    | '/deadlockdle'
    | '/deadlockstats-privacy'
    | '/flashcards'
    | '/games'
    | '/heatmap'
    | '/heroes'
    | '/ingest-cache'
    | '/items'
    | '/leaderboard'
    | '/patron'
    | '/players'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/team-builder'
    | '/tracker'
    | '/analytics/abilities'
    | '/analytics/games'
    | '/analytics/heroes'
    | '/analytics/items'
    | '/analytics/players'
    | '/analytics/team-builder'
    | '/blog/$slug'
    | '/community/badge-distribution'
    | '/community/heatmap'
    | '/community/leaderboard'
    | '/deadlockdle/guess-ability'
    | '/deadlockdle/guess-hero'
    | '/deadlockdle/guess-item'
    | '/deadlockdle/guess-sound'
    | '/deadlockdle/item-stats'
    | '/deadlockdle/trivia'
    | '/flashcards/heroes'
    | '/flashcards/item-effects'
    | '/flashcards/item-upgrades'
    | '/flashcards/items'
    | '/heroes/$heroName'
    | '/items/$itemName'
    | '/players_/$accountId'
    | '/analytics/'
    | '/blog/'
    | '/community/'
    | '/deadlockdle/'
    | '/flashcards/'
    | '/heroes/'
    | '/items/'
    | '/streamkit/'
    | '/analytics/heroes/$heroName'
    | '/analytics/items/$itemName'
    | '/auth/patreon/callback'
    | '/analytics/heroes/'
    | '/analytics/items/'
    | '/streamkit/widgets/$region/$accountId/$widgetType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbilitiesRoute: typeof AbilitiesRoute
  BadgeDistributionRoute: typeof BadgeDistributionRoute
  DataDumpsRoute: typeof DataDumpsRoute
  DataPrivacyRoute: typeof DataPrivacyRoute
  DeadlockdleRoute: typeof DeadlockdleRouteWithChildren
  DeadlockstatsPrivacyRoute: typeof DeadlockstatsPrivacyRoute
  FlashcardsRoute: typeof FlashcardsRouteWithChildren
  GamesRoute: typeof GamesRoute
  HeatmapRoute: typeof HeatmapRoute
  HeroesRoute: typeof HeroesRouteWithChildren
  IngestCacheRoute: typeof IngestCacheRoute
  ItemsRoute: typeof ItemsRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  PatronRoute: typeof PatronRoute
  PlayersRoute: typeof PlayersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Sitemap_indexDotxmlRoute: typeof Sitemap_indexDotxmlRoute
  TeamBuilderRoute: typeof TeamBuilderRoute
  TrackerRoute: typeof TrackerRoute
  AnalyticsAbilitiesRoute: typeof AnalyticsAbilitiesRoute
  AnalyticsGamesRoute: typeof AnalyticsGamesRoute
  AnalyticsHeroesRoute: typeof AnalyticsHeroesRouteWithChildren
  AnalyticsItemsRoute: typeof AnalyticsItemsRouteWithChildren
  AnalyticsPlayersRoute: typeof AnalyticsPlayersRoute
  AnalyticsTeamBuilderRoute: typeof AnalyticsTeamBuilderRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CommunityBadgeDistributionRoute: typeof CommunityBadgeDistributionRoute
  CommunityHeatmapRoute: typeof CommunityHeatmapRoute
  CommunityLeaderboardRoute: typeof CommunityLeaderboardRoute
  PlayersAccountIdRoute: typeof PlayersAccountIdRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  StreamkitIndexRoute: typeof StreamkitIndexRoute
  AuthPatreonCallbackRoute: typeof AuthPatreonCallbackRoute
  StreamkitWidgetsRegionAccountIdWidgetTypeRoute: typeof StreamkitWidgetsRegionAccountIdWidgetTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abilities': {
      id: '/abilities'
      path: '/abilities'
      fullPath: '/abilities'
      preLoaderRoute: typeof AbilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge-distribution': {
      id: '/badge-distribution'
      path: '/badge-distribution'
      fullPath: '/badge-distribution'
      preLoaderRoute: typeof BadgeDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-dumps': {
      id: '/data-dumps'
      path: '/data-dumps'
      fullPath: '/data-dumps'
      preLoaderRoute: typeof DataDumpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-privacy': {
      id: '/data-privacy'
      path: '/data-privacy'
      fullPath: '/data-privacy'
      preLoaderRoute: typeof DataPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlockdle': {
      id: '/deadlockdle'
      path: '/deadlockdle'
      fullPath: '/deadlockdle'
      preLoaderRoute: typeof DeadlockdleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlockstats-privacy': {
      id: '/deadlockstats-privacy'
      path: '/deadlockstats-privacy'
      fullPath: '/deadlockstats-privacy'
      preLoaderRoute: typeof DeadlockstatsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest-cache': {
      id: '/ingest-cache'
      path: '/ingest-cache'
      fullPath: '/ingest-cache'
      preLoaderRoute: typeof IngestCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patron': {
      id: '/patron'
      path: '/patron'
      fullPath: '/patron'
      preLoaderRoute: typeof PatronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap_index.xml': {
      id: '/sitemap_index.xml'
      path: '/sitemap_index.xml'
      fullPath: '/sitemap_index.xml'
      preLoaderRoute: typeof Sitemap_indexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-builder': {
      id: '/team-builder'
      path: '/team-builder'
      fullPath: '/team-builder'
      preLoaderRoute: typeof TeamBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/abilities': {
      id: '/analytics/abilities'
      path: '/analytics/abilities'
      fullPath: '/analytics/abilities'
      preLoaderRoute: typeof AnalyticsAbilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/games': {
      id: '/analytics/games'
      path: '/analytics/games'
      fullPath: '/analytics/games'
      preLoaderRoute: typeof AnalyticsGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/heroes': {
      id: '/analytics/heroes'
      path: '/analytics/heroes'
      fullPath: '/analytics/heroes'
      preLoaderRoute: typeof AnalyticsHeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/items': {
      id: '/analytics/items'
      path: '/analytics/items'
      fullPath: '/analytics/items'
      preLoaderRoute: typeof AnalyticsItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/players': {
      id: '/analytics/players'
      path: '/analytics/players'
      fullPath: '/analytics/players'
      preLoaderRoute: typeof AnalyticsPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/team-builder': {
      id: '/analytics/team-builder'
      path: '/analytics/team-builder'
      fullPath: '/analytics/team-builder'
      preLoaderRoute: typeof AnalyticsTeamBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/badge-distribution': {
      id: '/community/badge-distribution'
      path: '/community/badge-distribution'
      fullPath: '/community/badge-distribution'
      preLoaderRoute: typeof CommunityBadgeDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/heatmap': {
      id: '/community/heatmap'
      path: '/community/heatmap'
      fullPath: '/community/heatmap'
      preLoaderRoute: typeof CommunityHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/leaderboard': {
      id: '/community/leaderboard'
      path: '/community/leaderboard'
      fullPath: '/community/leaderboard'
      preLoaderRoute: typeof CommunityLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlockdle/': {
      id: '/deadlockdle/'
      path: '/'
      fullPath: '/deadlockdle/'
      preLoaderRoute: typeof DeadlockdleIndexRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/guess-ability': {
      id: '/deadlockdle/guess-ability'
      path: '/guess-ability'
      fullPath: '/deadlockdle/guess-ability'
      preLoaderRoute: typeof DeadlockdleGuessAbilityRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/guess-hero': {
      id: '/deadlockdle/guess-hero'
      path: '/guess-hero'
      fullPath: '/deadlockdle/guess-hero'
      preLoaderRoute: typeof DeadlockdleGuessHeroRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/guess-item': {
      id: '/deadlockdle/guess-item'
      path: '/guess-item'
      fullPath: '/deadlockdle/guess-item'
      preLoaderRoute: typeof DeadlockdleGuessItemRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/guess-sound': {
      id: '/deadlockdle/guess-sound'
      path: '/guess-sound'
      fullPath: '/deadlockdle/guess-sound'
      preLoaderRoute: typeof DeadlockdleGuessSoundRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/item-stats': {
      id: '/deadlockdle/item-stats'
      path: '/item-stats'
      fullPath: '/deadlockdle/item-stats'
      preLoaderRoute: typeof DeadlockdleItemStatsRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/trivia': {
      id: '/deadlockdle/trivia'
      path: '/trivia'
      fullPath: '/deadlockdle/trivia'
      preLoaderRoute: typeof DeadlockdleTriviaRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/flashcards/': {
      id: '/flashcards/'
      path: '/'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof FlashcardsIndexRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/flashcards/heroes': {
      id: '/flashcards/heroes'
      path: '/heroes'
      fullPath: '/flashcards/heroes'
      preLoaderRoute: typeof FlashcardsHeroesRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/flashcards/item-effects': {
      id: '/flashcards/item-effects'
      path: '/item-effects'
      fullPath: '/flashcards/item-effects'
      preLoaderRoute: typeof FlashcardsItemEffectsRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/flashcards/item-upgrades': {
      id: '/flashcards/item-upgrades'
      path: '/item-upgrades'
      fullPath: '/flashcards/item-upgrades'
      preLoaderRoute: typeof FlashcardsItemUpgradesRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/flashcards/items': {
      id: '/flashcards/items'
      path: '/items'
      fullPath: '/flashcards/items'
      preLoaderRoute: typeof FlashcardsItemsRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/heroes/': {
      id: '/heroes/'
      path: '/'
      fullPath: '/heroes/'
      preLoaderRoute: typeof HeroesIndexRouteImport
      parentRoute: typeof HeroesRoute
    }
    '/heroes/$heroName': {
      id: '/heroes/$heroName'
      path: '/$heroName'
      fullPath: '/heroes/$heroName'
      preLoaderRoute: typeof HeroesHeroNameRouteImport
      parentRoute: typeof HeroesRoute
    }
    '/items/': {
      id: '/items/'
      path: '/'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/$itemName': {
      id: '/items/$itemName'
      path: '/$itemName'
      fullPath: '/items/$itemName'
      preLoaderRoute: typeof ItemsItemNameRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/players_/$accountId': {
      id: '/players_/$accountId'
      path: '/players/$accountId'
      fullPath: '/players/$accountId'
      preLoaderRoute: typeof PlayersAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamkit/': {
      id: '/streamkit/'
      path: '/streamkit'
      fullPath: '/streamkit/'
      preLoaderRoute: typeof StreamkitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/heroes/': {
      id: '/analytics/heroes/'
      path: '/'
      fullPath: '/analytics/heroes/'
      preLoaderRoute: typeof AnalyticsHeroesIndexRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/heroes/$heroName': {
      id: '/analytics/heroes/$heroName'
      path: '/$heroName'
      fullPath: '/analytics/heroes/$heroName'
      preLoaderRoute: typeof AnalyticsHeroesHeroNameRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/items/': {
      id: '/analytics/items/'
      path: '/'
      fullPath: '/analytics/items/'
      preLoaderRoute: typeof AnalyticsItemsIndexRouteImport
      parentRoute: typeof AnalyticsItemsRoute
    }
    '/analytics/items/$itemName': {
      id: '/analytics/items/$itemName'
      path: '/$itemName'
      fullPath: '/analytics/items/$itemName'
      preLoaderRoute: typeof AnalyticsItemsItemNameRouteImport
      parentRoute: typeof AnalyticsItemsRoute
    }
    '/auth/patreon/callback': {
      id: '/auth/patreon/callback'
      path: '/auth/patreon/callback'
      fullPath: '/auth/patreon/callback'
      preLoaderRoute: typeof AuthPatreonCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamkit/widgets/$region/$accountId/$widgetType': {
      id: '/streamkit/widgets/$region/$accountId/$widgetType'
      path: '/streamkit/widgets/$region/$accountId/$widgetType'
      fullPath: '/streamkit/widgets/$region/$accountId/$widgetType'
      preLoaderRoute: typeof StreamkitWidgetsRegionAccountIdWidgetTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeadlockdleRouteChildren {
  DeadlockdleGuessAbilityRoute: typeof DeadlockdleGuessAbilityRoute
  DeadlockdleGuessHeroRoute: typeof DeadlockdleGuessHeroRoute
  DeadlockdleGuessItemRoute: typeof DeadlockdleGuessItemRoute
  DeadlockdleGuessSoundRoute: typeof DeadlockdleGuessSoundRoute
  DeadlockdleItemStatsRoute: typeof DeadlockdleItemStatsRoute
  DeadlockdleTriviaRoute: typeof DeadlockdleTriviaRoute
  DeadlockdleIndexRoute: typeof DeadlockdleIndexRoute
}

const DeadlockdleRouteChildren: DeadlockdleRouteChildren = {
  DeadlockdleGuessAbilityRoute: DeadlockdleGuessAbilityRoute,
  DeadlockdleGuessHeroRoute: DeadlockdleGuessHeroRoute,
  DeadlockdleGuessItemRoute: DeadlockdleGuessItemRoute,
  DeadlockdleGuessSoundRoute: DeadlockdleGuessSoundRoute,
  DeadlockdleItemStatsRoute: DeadlockdleItemStatsRoute,
  DeadlockdleTriviaRoute: DeadlockdleTriviaRoute,
  DeadlockdleIndexRoute: DeadlockdleIndexRoute,
}

const DeadlockdleRouteWithChildren = DeadlockdleRoute._addFileChildren(
  DeadlockdleRouteChildren,
)

interface FlashcardsRouteChildren {
  FlashcardsHeroesRoute: typeof FlashcardsHeroesRoute
  FlashcardsItemEffectsRoute: typeof FlashcardsItemEffectsRoute
  FlashcardsItemUpgradesRoute: typeof FlashcardsItemUpgradesRoute
  FlashcardsItemsRoute: typeof FlashcardsItemsRoute
  FlashcardsIndexRoute: typeof FlashcardsIndexRoute
}

const FlashcardsRouteChildren: FlashcardsRouteChildren = {
  FlashcardsHeroesRoute: FlashcardsHeroesRoute,
  FlashcardsItemEffectsRoute: FlashcardsItemEffectsRoute,
  FlashcardsItemUpgradesRoute: FlashcardsItemUpgradesRoute,
  FlashcardsItemsRoute: FlashcardsItemsRoute,
  FlashcardsIndexRoute: FlashcardsIndexRoute,
}

const FlashcardsRouteWithChildren = FlashcardsRoute._addFileChildren(
  FlashcardsRouteChildren,
)

interface HeroesRouteChildren {
  HeroesHeroNameRoute: typeof HeroesHeroNameRoute
  HeroesIndexRoute: typeof HeroesIndexRoute
}

const HeroesRouteChildren: HeroesRouteChildren = {
  HeroesHeroNameRoute: HeroesHeroNameRoute,
  HeroesIndexRoute: HeroesIndexRoute,
}

const HeroesRouteWithChildren =
  HeroesRoute._addFileChildren(HeroesRouteChildren)

interface ItemsRouteChildren {
  ItemsItemNameRoute: typeof ItemsItemNameRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsItemNameRoute: ItemsItemNameRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

interface AnalyticsHeroesRouteChildren {
  AnalyticsHeroesHeroNameRoute: typeof AnalyticsHeroesHeroNameRoute
  AnalyticsHeroesIndexRoute: typeof AnalyticsHeroesIndexRoute
}

const AnalyticsHeroesRouteChildren: AnalyticsHeroesRouteChildren = {
  AnalyticsHeroesHeroNameRoute: AnalyticsHeroesHeroNameRoute,
  AnalyticsHeroesIndexRoute: AnalyticsHeroesIndexRoute,
}

const AnalyticsHeroesRouteWithChildren = AnalyticsHeroesRoute._addFileChildren(
  AnalyticsHeroesRouteChildren,
)

interface AnalyticsItemsRouteChildren {
  AnalyticsItemsItemNameRoute: typeof AnalyticsItemsItemNameRoute
  AnalyticsItemsIndexRoute: typeof AnalyticsItemsIndexRoute
}

const AnalyticsItemsRouteChildren: AnalyticsItemsRouteChildren = {
  AnalyticsItemsItemNameRoute: AnalyticsItemsItemNameRoute,
  AnalyticsItemsIndexRoute: AnalyticsItemsIndexRoute,
}

const AnalyticsItemsRouteWithChildren = AnalyticsItemsRoute._addFileChildren(
  AnalyticsItemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbilitiesRoute: AbilitiesRoute,
  BadgeDistributionRoute: BadgeDistributionRoute,
  DataDumpsRoute: DataDumpsRoute,
  DataPrivacyRoute: DataPrivacyRoute,
  DeadlockdleRoute: DeadlockdleRouteWithChildren,
  DeadlockstatsPrivacyRoute: DeadlockstatsPrivacyRoute,
  FlashcardsRoute: FlashcardsRouteWithChildren,
  GamesRoute: GamesRoute,
  HeatmapRoute: HeatmapRoute,
  HeroesRoute: HeroesRouteWithChildren,
  IngestCacheRoute: IngestCacheRoute,
  ItemsRoute: ItemsRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  PatronRoute: PatronRoute,
  PlayersRoute: PlayersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Sitemap_indexDotxmlRoute: Sitemap_indexDotxmlRoute,
  TeamBuilderRoute: TeamBuilderRoute,
  TrackerRoute: TrackerRoute,
  AnalyticsAbilitiesRoute: AnalyticsAbilitiesRoute,
  AnalyticsGamesRoute: AnalyticsGamesRoute,
  AnalyticsHeroesRoute: AnalyticsHeroesRouteWithChildren,
  AnalyticsItemsRoute: AnalyticsItemsRouteWithChildren,
  AnalyticsPlayersRoute: AnalyticsPlayersRoute,
  AnalyticsTeamBuilderRoute: AnalyticsTeamBuilderRoute,
  BlogSlugRoute: BlogSlugRoute,
  CommunityBadgeDistributionRoute: CommunityBadgeDistributionRoute,
  CommunityHeatmapRoute: CommunityHeatmapRoute,
  CommunityLeaderboardRoute: CommunityLeaderboardRoute,
  PlayersAccountIdRoute: PlayersAccountIdRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  StreamkitIndexRoute: StreamkitIndexRoute,
  AuthPatreonCallbackRoute: AuthPatreonCallbackRoute,
  StreamkitWidgetsRegionAccountIdWidgetTypeRoute:
    StreamkitWidgetsRegionAccountIdWidgetTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
