/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbilitiesRouteImport } from './routes/abilities'
import { Route as BadgeDistributionRouteImport } from './routes/badge-distribution'
import { Route as DataDumpsRouteImport } from './routes/data-dumps'
import { Route as DataPrivacyRouteImport } from './routes/data-privacy'
import { Route as DeadlockdleRouteImport } from './routes/deadlockdle'
import { Route as DeadlockstatsPrivacyRouteImport } from './routes/deadlockstats-privacy'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as GamesRouteImport } from './routes/games'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as HeroesRouteImport } from './routes/heroes'
import { Route as IngestCacheRouteImport } from './routes/ingest-cache'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PatronRouteImport } from './routes/patron'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Sitemap_indexDotxmlRouteImport } from './routes/sitemap_index[.]xml'
import { Route as TeamBuilderRouteImport } from './routes/team-builder'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as AnalyticsAbilitiesRouteImport } from './routes/analytics.abilities'
import { Route as AnalyticsGamesRouteImport } from './routes/analytics.games'
import { Route as AnalyticsHeroesRouteImport } from './routes/analytics.heroes'
import { Route as AnalyticsItemsRouteImport } from './routes/analytics.items'
import { Route as AnalyticsPlayersRouteImport } from './routes/analytics.players'
import { Route as AnalyticsTeamBuilderRouteImport } from './routes/analytics.team-builder'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunityBadgeDistributionRouteImport } from './routes/community.badge-distribution'
import { Route as CommunityHeatmapRouteImport } from './routes/community.heatmap'
import { Route as CommunityLeaderboardRouteImport } from './routes/community.leaderboard'
import { Route as DeadlockdleIndexRouteImport } from './routes/deadlockdle/index'
import { Route as DeadlockdleGuessAbilityRouteImport } from './routes/deadlockdle/guess-ability'
import { Route as DeadlockdleGuessHeroRouteImport } from './routes/deadlockdle/guess-hero'
import { Route as DeadlockdleGuessItemRouteImport } from './routes/deadlockdle/guess-item'
import { Route as DeadlockdleGuessSoundRouteImport } from './routes/deadlockdle/guess-sound'
import { Route as DeadlockdleItemStatsRouteImport } from './routes/deadlockdle/item-stats'
import { Route as DeadlockdleTriviaRouteImport } from './routes/deadlockdle/trivia'
import { Route as DevDesignSystemRouteImport } from './routes/dev.design-system'
import { Route as FlashcardsIndexRouteImport } from './routes/flashcards/index'
import { Route as FlashcardsHeroesRouteImport } from './routes/flashcards/heroes'
import { Route as FlashcardsItemEffectsRouteImport } from './routes/flashcards/item-effects'
import { Route as FlashcardsItemUpgradesRouteImport } from './routes/flashcards/item-upgrades'
import { Route as FlashcardsItemsRouteImport } from './routes/flashcards/items'
import { Route as GamesDeadlockdleRouteImport } from './routes/games_.deadlockdle'
import { Route as GamesFlashcardsRouteImport } from './routes/games_.flashcards'
import { Route as HeroesIndexRouteImport } from './routes/heroes.index'
import { Route as HeroesHeroNameRouteImport } from './routes/heroes.$heroName'
import { Route as ItemsIndexRouteImport } from './routes/items.index'
import { Route as ItemsItemNameRouteImport } from './routes/items.$itemName'
import { Route as PlayersAccountIdRouteImport } from './routes/players_.$accountId'
import { Route as StreamkitIndexRouteImport } from './routes/streamkit/index'
import { Route as TrackerDemoRouteImport } from './routes/tracker_.demo'
import { Route as AnalyticsGamesIndexRouteImport } from './routes/analytics.games.index'
import { Route as AnalyticsGamesByRankRouteImport } from './routes/analytics.games.by-rank'
import { Route as AnalyticsGamesEconomyRouteImport } from './routes/analytics.games.economy'
import { Route as AnalyticsGamesOverTimeRouteImport } from './routes/analytics.games.over-time'
import { Route as AnalyticsHeroesIndexRouteImport } from './routes/analytics.heroes.index'
import { Route as AnalyticsHeroesHeroNameRouteImport } from './routes/analytics.heroes.$heroName'
import { Route as AnalyticsHeroesByDurationRouteImport } from './routes/analytics.heroes.by-duration'
import { Route as AnalyticsHeroesByExperienceRouteImport } from './routes/analytics.heroes.by-experience'
import { Route as AnalyticsHeroesByRankRouteImport } from './routes/analytics.heroes.by-rank'
import { Route as AnalyticsHeroesCombosRouteImport } from './routes/analytics.heroes.combos'
import { Route as AnalyticsHeroesMatchupDetailsRouteImport } from './routes/analytics.heroes.matchup-details'
import { Route as AnalyticsHeroesMatchupsRouteImport } from './routes/analytics.heroes.matchups'
import { Route as AnalyticsHeroesOverTimeRouteImport } from './routes/analytics.heroes.over-time'
import { Route as AnalyticsHeroesScoreboardRouteImport } from './routes/analytics.heroes.scoreboard'
import { Route as AnalyticsItemsIndexRouteImport } from './routes/analytics.items.index'
import { Route as AnalyticsItemsItemNameRouteImport } from './routes/analytics.items.$itemName'
import { Route as AnalyticsItemsBuildFlowRouteImport } from './routes/analytics.items.build-flow'
import { Route as AnalyticsItemsCombosRouteImport } from './routes/analytics.items.combos'
import { Route as AnalyticsItemsItemPurchaseAnalysisRouteImport } from './routes/analytics.items.item-purchase-analysis'
import { Route as AnalyticsPlayersIndexRouteImport } from './routes/analytics.players.index'
import { Route as AnalyticsPlayersStatsMetricsRouteImport } from './routes/analytics.players.stats-metrics'
import { Route as AuthPatreonCallbackRouteImport } from './routes/auth/patreon/callback'
import { Route as GamesDeadlockdleIndexRouteImport } from './routes/games_.deadlockdle/index'
import { Route as GamesDeadlockdleGuessAbilityRouteImport } from './routes/games_.deadlockdle/guess-ability'
import { Route as GamesDeadlockdleGuessHeroRouteImport } from './routes/games_.deadlockdle/guess-hero'
import { Route as GamesDeadlockdleGuessItemRouteImport } from './routes/games_.deadlockdle/guess-item'
import { Route as GamesDeadlockdleGuessSoundRouteImport } from './routes/games_.deadlockdle/guess-sound'
import { Route as GamesDeadlockdleItemStatsRouteImport } from './routes/games_.deadlockdle/item-stats'
import { Route as GamesDeadlockdleTriviaRouteImport } from './routes/games_.deadlockdle/trivia'
import { Route as GamesFlashcardsIndexRouteImport } from './routes/games_.flashcards/index'
import { Route as GamesFlashcardsHeroesRouteImport } from './routes/games_.flashcards/heroes'
import { Route as GamesFlashcardsItemEffectsRouteImport } from './routes/games_.flashcards/item-effects'
import { Route as GamesFlashcardsItemUpgradesRouteImport } from './routes/games_.flashcards/item-upgrades'
import { Route as GamesFlashcardsItemsRouteImport } from './routes/games_.flashcards/items'
import { Route as TrackerPlayersIndexRouteImport } from './routes/tracker_.players.index'
import { Route as TrackerPlayersAccountIdRouteImport } from './routes/tracker_.players.$accountId'
import { Route as StreamkitWidgetsRegionAccountIdWidgetTypeRouteImport } from './routes/streamkit/widgets/$region/$accountId/$widgetType'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbilitiesRoute = AbilitiesRouteImport.update({
  id: '/abilities',
  path: '/abilities',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeDistributionRoute = BadgeDistributionRouteImport.update({
  id: '/badge-distribution',
  path: '/badge-distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDumpsRoute = DataDumpsRouteImport.update({
  id: '/data-dumps',
  path: '/data-dumps',
  getParentRoute: () => rootRouteImport,
} as any)
const DataPrivacyRoute = DataPrivacyRouteImport.update({
  id: '/data-privacy',
  path: '/data-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlockdleRoute = DeadlockdleRouteImport.update({
  id: '/deadlockdle',
  path: '/deadlockdle',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlockstatsPrivacyRoute = DeadlockstatsPrivacyRouteImport.update({
  id: '/deadlockstats-privacy',
  path: '/deadlockstats-privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesRoute = HeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestCacheRoute = IngestCacheRouteImport.update({
  id: '/ingest-cache',
  path: '/ingest-cache',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PatronRoute = PatronRouteImport.update({
  id: '/patron',
  path: '/patron',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Sitemap_indexDotxmlRoute = Sitemap_indexDotxmlRouteImport.update({
  id: '/sitemap_index.xml',
  path: '/sitemap_index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamBuilderRoute = TeamBuilderRouteImport.update({
  id: '/team-builder',
  path: '/team-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsAbilitiesRoute = AnalyticsAbilitiesRouteImport.update({
  id: '/analytics/abilities',
  path: '/analytics/abilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsGamesRoute = AnalyticsGamesRouteImport.update({
  id: '/analytics/games',
  path: '/analytics/games',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsHeroesRoute = AnalyticsHeroesRouteImport.update({
  id: '/analytics/heroes',
  path: '/analytics/heroes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsItemsRoute = AnalyticsItemsRouteImport.update({
  id: '/analytics/items',
  path: '/analytics/items',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsPlayersRoute = AnalyticsPlayersRouteImport.update({
  id: '/analytics/players',
  path: '/analytics/players',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsTeamBuilderRoute = AnalyticsTeamBuilderRouteImport.update({
  id: '/analytics/team-builder',
  path: '/analytics/team-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityBadgeDistributionRoute =
  CommunityBadgeDistributionRouteImport.update({
    id: '/community/badge-distribution',
    path: '/community/badge-distribution',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommunityHeatmapRoute = CommunityHeatmapRouteImport.update({
  id: '/community/heatmap',
  path: '/community/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityLeaderboardRoute = CommunityLeaderboardRouteImport.update({
  id: '/community/leaderboard',
  path: '/community/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadlockdleIndexRoute = DeadlockdleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleGuessAbilityRoute = DeadlockdleGuessAbilityRouteImport.update({
  id: '/guess-ability',
  path: '/guess-ability',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleGuessHeroRoute = DeadlockdleGuessHeroRouteImport.update({
  id: '/guess-hero',
  path: '/guess-hero',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleGuessItemRoute = DeadlockdleGuessItemRouteImport.update({
  id: '/guess-item',
  path: '/guess-item',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleGuessSoundRoute = DeadlockdleGuessSoundRouteImport.update({
  id: '/guess-sound',
  path: '/guess-sound',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleItemStatsRoute = DeadlockdleItemStatsRouteImport.update({
  id: '/item-stats',
  path: '/item-stats',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DeadlockdleTriviaRoute = DeadlockdleTriviaRouteImport.update({
  id: '/trivia',
  path: '/trivia',
  getParentRoute: () => DeadlockdleRoute,
} as any)
const DevDesignSystemRoute = DevDesignSystemRouteImport.update({
  id: '/dev/design-system',
  path: '/dev/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsIndexRoute = FlashcardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FlashcardsRoute,
} as any)
const FlashcardsHeroesRoute = FlashcardsHeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => FlashcardsRoute,
} as any)
const FlashcardsItemEffectsRoute = FlashcardsItemEffectsRouteImport.update({
  id: '/item-effects',
  path: '/item-effects',
  getParentRoute: () => FlashcardsRoute,
} as any)
const FlashcardsItemUpgradesRoute = FlashcardsItemUpgradesRouteImport.update({
  id: '/item-upgrades',
  path: '/item-upgrades',
  getParentRoute: () => FlashcardsRoute,
} as any)
const FlashcardsItemsRoute = FlashcardsItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => FlashcardsRoute,
} as any)
const GamesDeadlockdleRoute = GamesDeadlockdleRouteImport.update({
  id: '/games_/deadlockdle',
  path: '/games/deadlockdle',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesFlashcardsRoute = GamesFlashcardsRouteImport.update({
  id: '/games_/flashcards',
  path: '/games/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesIndexRoute = HeroesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HeroesRoute,
} as any)
const HeroesHeroNameRoute = HeroesHeroNameRouteImport.update({
  id: '/$heroName',
  path: '/$heroName',
  getParentRoute: () => HeroesRoute,
} as any)
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItemsRoute,
} as any)
const ItemsItemNameRoute = ItemsItemNameRouteImport.update({
  id: '/$itemName',
  path: '/$itemName',
  getParentRoute: () => ItemsRoute,
} as any)
const PlayersAccountIdRoute = PlayersAccountIdRouteImport.update({
  id: '/players_/$accountId',
  path: '/players/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamkitIndexRoute = StreamkitIndexRouteImport.update({
  id: '/streamkit/',
  path: '/streamkit/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerDemoRoute = TrackerDemoRouteImport.update({
  id: '/tracker_/demo',
  path: '/tracker/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsGamesIndexRoute = AnalyticsGamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsGamesRoute,
} as any)
const AnalyticsGamesByRankRoute = AnalyticsGamesByRankRouteImport.update({
  id: '/by-rank',
  path: '/by-rank',
  getParentRoute: () => AnalyticsGamesRoute,
} as any)
const AnalyticsGamesEconomyRoute = AnalyticsGamesEconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => AnalyticsGamesRoute,
} as any)
const AnalyticsGamesOverTimeRoute = AnalyticsGamesOverTimeRouteImport.update({
  id: '/over-time',
  path: '/over-time',
  getParentRoute: () => AnalyticsGamesRoute,
} as any)
const AnalyticsHeroesIndexRoute = AnalyticsHeroesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsHeroesRoute,
} as any)
const AnalyticsHeroesHeroNameRoute = AnalyticsHeroesHeroNameRouteImport.update({
  id: '/$heroName',
  path: '/$heroName',
  getParentRoute: () => AnalyticsHeroesRoute,
} as any)
const AnalyticsHeroesByDurationRoute =
  AnalyticsHeroesByDurationRouteImport.update({
    id: '/by-duration',
    path: '/by-duration',
    getParentRoute: () => AnalyticsHeroesRoute,
  } as any)
const AnalyticsHeroesByExperienceRoute =
  AnalyticsHeroesByExperienceRouteImport.update({
    id: '/by-experience',
    path: '/by-experience',
    getParentRoute: () => AnalyticsHeroesRoute,
  } as any)
const AnalyticsHeroesByRankRoute = AnalyticsHeroesByRankRouteImport.update({
  id: '/by-rank',
  path: '/by-rank',
  getParentRoute: () => AnalyticsHeroesRoute,
} as any)
const AnalyticsHeroesCombosRoute = AnalyticsHeroesCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AnalyticsHeroesRoute,
} as any)
const AnalyticsHeroesMatchupDetailsRoute =
  AnalyticsHeroesMatchupDetailsRouteImport.update({
    id: '/matchup-details',
    path: '/matchup-details',
    getParentRoute: () => AnalyticsHeroesRoute,
  } as any)
const AnalyticsHeroesMatchupsRoute = AnalyticsHeroesMatchupsRouteImport.update({
  id: '/matchups',
  path: '/matchups',
  getParentRoute: () => AnalyticsHeroesRoute,
} as any)
const AnalyticsHeroesOverTimeRoute = AnalyticsHeroesOverTimeRouteImport.update({
  id: '/over-time',
  path: '/over-time',
  getParentRoute: () => AnalyticsHeroesRoute,
} as any)
const AnalyticsHeroesScoreboardRoute =
  AnalyticsHeroesScoreboardRouteImport.update({
    id: '/scoreboard',
    path: '/scoreboard',
    getParentRoute: () => AnalyticsHeroesRoute,
  } as any)
const AnalyticsItemsIndexRoute = AnalyticsItemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsItemsRoute,
} as any)
const AnalyticsItemsItemNameRoute = AnalyticsItemsItemNameRouteImport.update({
  id: '/$itemName',
  path: '/$itemName',
  getParentRoute: () => AnalyticsItemsRoute,
} as any)
const AnalyticsItemsBuildFlowRoute = AnalyticsItemsBuildFlowRouteImport.update({
  id: '/build-flow',
  path: '/build-flow',
  getParentRoute: () => AnalyticsItemsRoute,
} as any)
const AnalyticsItemsCombosRoute = AnalyticsItemsCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AnalyticsItemsRoute,
} as any)
const AnalyticsItemsItemPurchaseAnalysisRoute =
  AnalyticsItemsItemPurchaseAnalysisRouteImport.update({
    id: '/item-purchase-analysis',
    path: '/item-purchase-analysis',
    getParentRoute: () => AnalyticsItemsRoute,
  } as any)
const AnalyticsPlayersIndexRoute = AnalyticsPlayersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsPlayersRoute,
} as any)
const AnalyticsPlayersStatsMetricsRoute =
  AnalyticsPlayersStatsMetricsRouteImport.update({
    id: '/stats-metrics',
    path: '/stats-metrics',
    getParentRoute: () => AnalyticsPlayersRoute,
  } as any)
const AuthPatreonCallbackRoute = AuthPatreonCallbackRouteImport.update({
  id: '/auth/patreon/callback',
  path: '/auth/patreon/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDeadlockdleIndexRoute = GamesDeadlockdleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesDeadlockdleRoute,
} as any)
const GamesDeadlockdleGuessAbilityRoute =
  GamesDeadlockdleGuessAbilityRouteImport.update({
    id: '/guess-ability',
    path: '/guess-ability',
    getParentRoute: () => GamesDeadlockdleRoute,
  } as any)
const GamesDeadlockdleGuessHeroRoute =
  GamesDeadlockdleGuessHeroRouteImport.update({
    id: '/guess-hero',
    path: '/guess-hero',
    getParentRoute: () => GamesDeadlockdleRoute,
  } as any)
const GamesDeadlockdleGuessItemRoute =
  GamesDeadlockdleGuessItemRouteImport.update({
    id: '/guess-item',
    path: '/guess-item',
    getParentRoute: () => GamesDeadlockdleRoute,
  } as any)
const GamesDeadlockdleGuessSoundRoute =
  GamesDeadlockdleGuessSoundRouteImport.update({
    id: '/guess-sound',
    path: '/guess-sound',
    getParentRoute: () => GamesDeadlockdleRoute,
  } as any)
const GamesDeadlockdleItemStatsRoute =
  GamesDeadlockdleItemStatsRouteImport.update({
    id: '/item-stats',
    path: '/item-stats',
    getParentRoute: () => GamesDeadlockdleRoute,
  } as any)
const GamesDeadlockdleTriviaRoute = GamesDeadlockdleTriviaRouteImport.update({
  id: '/trivia',
  path: '/trivia',
  getParentRoute: () => GamesDeadlockdleRoute,
} as any)
const GamesFlashcardsIndexRoute = GamesFlashcardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesFlashcardsRoute,
} as any)
const GamesFlashcardsHeroesRoute = GamesFlashcardsHeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => GamesFlashcardsRoute,
} as any)
const GamesFlashcardsItemEffectsRoute =
  GamesFlashcardsItemEffectsRouteImport.update({
    id: '/item-effects',
    path: '/item-effects',
    getParentRoute: () => GamesFlashcardsRoute,
  } as any)
const GamesFlashcardsItemUpgradesRoute =
  GamesFlashcardsItemUpgradesRouteImport.update({
    id: '/item-upgrades',
    path: '/item-upgrades',
    getParentRoute: () => GamesFlashcardsRoute,
  } as any)
const GamesFlashcardsItemsRoute = GamesFlashcardsItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => GamesFlashcardsRoute,
} as any)
const TrackerPlayersIndexRoute = TrackerPlayersIndexRouteImport.update({
  id: '/tracker_/players/',
  path: '/tracker/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerPlayersAccountIdRoute = TrackerPlayersAccountIdRouteImport.update({
  id: '/tracker_/players/$accountId',
  path: '/tracker/players/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamkitWidgetsRegionAccountIdWidgetTypeRoute =
  StreamkitWidgetsRegionAccountIdWidgetTypeRouteImport.update({
    id: '/streamkit/widgets/$region/$accountId/$widgetType',
    path: '/streamkit/widgets/$region/$accountId/$widgetType',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abilities': typeof AbilitiesRoute
  '/badge-distribution': typeof BadgeDistributionRoute
  '/data-dumps': typeof DataDumpsRoute
  '/data-privacy': typeof DataPrivacyRoute
  '/deadlockdle': typeof DeadlockdleRouteWithChildren
  '/deadlockstats-privacy': typeof DeadlockstatsPrivacyRoute
  '/flashcards': typeof FlashcardsRouteWithChildren
  '/games': typeof GamesRoute
  '/heatmap': typeof HeatmapRoute
  '/heroes': typeof HeroesRouteWithChildren
  '/ingest-cache': typeof IngestCacheRoute
  '/items': typeof ItemsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/patron': typeof PatronRoute
  '/players': typeof PlayersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/team-builder': typeof TeamBuilderRoute
  '/tracker': typeof TrackerRoute
  '/analytics/abilities': typeof AnalyticsAbilitiesRoute
  '/analytics/games': typeof AnalyticsGamesRouteWithChildren
  '/analytics/heroes': typeof AnalyticsHeroesRouteWithChildren
  '/analytics/items': typeof AnalyticsItemsRouteWithChildren
  '/analytics/players': typeof AnalyticsPlayersRouteWithChildren
  '/analytics/team-builder': typeof AnalyticsTeamBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/badge-distribution': typeof CommunityBadgeDistributionRoute
  '/community/heatmap': typeof CommunityHeatmapRoute
  '/community/leaderboard': typeof CommunityLeaderboardRoute
  '/deadlockdle/guess-ability': typeof DeadlockdleGuessAbilityRoute
  '/deadlockdle/guess-hero': typeof DeadlockdleGuessHeroRoute
  '/deadlockdle/guess-item': typeof DeadlockdleGuessItemRoute
  '/deadlockdle/guess-sound': typeof DeadlockdleGuessSoundRoute
  '/deadlockdle/item-stats': typeof DeadlockdleItemStatsRoute
  '/deadlockdle/trivia': typeof DeadlockdleTriviaRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/flashcards/heroes': typeof FlashcardsHeroesRoute
  '/flashcards/item-effects': typeof FlashcardsItemEffectsRoute
  '/flashcards/item-upgrades': typeof FlashcardsItemUpgradesRoute
  '/flashcards/items': typeof FlashcardsItemsRoute
  '/games/deadlockdle': typeof GamesDeadlockdleRouteWithChildren
  '/games/flashcards': typeof GamesFlashcardsRouteWithChildren
  '/heroes/$heroName': typeof HeroesHeroNameRoute
  '/items/$itemName': typeof ItemsItemNameRoute
  '/players/$accountId': typeof PlayersAccountIdRoute
  '/tracker/demo': typeof TrackerDemoRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/deadlockdle/': typeof DeadlockdleIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/heroes/': typeof HeroesIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/streamkit/': typeof StreamkitIndexRoute
  '/analytics/games/by-rank': typeof AnalyticsGamesByRankRoute
  '/analytics/games/economy': typeof AnalyticsGamesEconomyRoute
  '/analytics/games/over-time': typeof AnalyticsGamesOverTimeRoute
  '/analytics/heroes/$heroName': typeof AnalyticsHeroesHeroNameRoute
  '/analytics/heroes/by-duration': typeof AnalyticsHeroesByDurationRoute
  '/analytics/heroes/by-experience': typeof AnalyticsHeroesByExperienceRoute
  '/analytics/heroes/by-rank': typeof AnalyticsHeroesByRankRoute
  '/analytics/heroes/combos': typeof AnalyticsHeroesCombosRoute
  '/analytics/heroes/matchup-details': typeof AnalyticsHeroesMatchupDetailsRoute
  '/analytics/heroes/matchups': typeof AnalyticsHeroesMatchupsRoute
  '/analytics/heroes/over-time': typeof AnalyticsHeroesOverTimeRoute
  '/analytics/heroes/scoreboard': typeof AnalyticsHeroesScoreboardRoute
  '/analytics/items/$itemName': typeof AnalyticsItemsItemNameRoute
  '/analytics/items/build-flow': typeof AnalyticsItemsBuildFlowRoute
  '/analytics/items/combos': typeof AnalyticsItemsCombosRoute
  '/analytics/items/item-purchase-analysis': typeof AnalyticsItemsItemPurchaseAnalysisRoute
  '/analytics/players/stats-metrics': typeof AnalyticsPlayersStatsMetricsRoute
  '/auth/patreon/callback': typeof AuthPatreonCallbackRoute
  '/games/deadlockdle/guess-ability': typeof GamesDeadlockdleGuessAbilityRoute
  '/games/deadlockdle/guess-hero': typeof GamesDeadlockdleGuessHeroRoute
  '/games/deadlockdle/guess-item': typeof GamesDeadlockdleGuessItemRoute
  '/games/deadlockdle/guess-sound': typeof GamesDeadlockdleGuessSoundRoute
  '/games/deadlockdle/item-stats': typeof GamesDeadlockdleItemStatsRoute
  '/games/deadlockdle/trivia': typeof GamesDeadlockdleTriviaRoute
  '/games/flashcards/heroes': typeof GamesFlashcardsHeroesRoute
  '/games/flashcards/item-effects': typeof GamesFlashcardsItemEffectsRoute
  '/games/flashcards/item-upgrades': typeof GamesFlashcardsItemUpgradesRoute
  '/games/flashcards/items': typeof GamesFlashcardsItemsRoute
  '/tracker/players/$accountId': typeof TrackerPlayersAccountIdRoute
  '/analytics/games/': typeof AnalyticsGamesIndexRoute
  '/analytics/heroes/': typeof AnalyticsHeroesIndexRoute
  '/analytics/items/': typeof AnalyticsItemsIndexRoute
  '/analytics/players/': typeof AnalyticsPlayersIndexRoute
  '/games/deadlockdle/': typeof GamesDeadlockdleIndexRoute
  '/games/flashcards/': typeof GamesFlashcardsIndexRoute
  '/tracker/players/': typeof TrackerPlayersIndexRoute
  '/streamkit/widgets/$region/$accountId/$widgetType': typeof StreamkitWidgetsRegionAccountIdWidgetTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abilities': typeof AbilitiesRoute
  '/badge-distribution': typeof BadgeDistributionRoute
  '/data-dumps': typeof DataDumpsRoute
  '/data-privacy': typeof DataPrivacyRoute
  '/deadlockstats-privacy': typeof DeadlockstatsPrivacyRoute
  '/games': typeof GamesRoute
  '/heatmap': typeof HeatmapRoute
  '/ingest-cache': typeof IngestCacheRoute
  '/leaderboard': typeof LeaderboardRoute
  '/patron': typeof PatronRoute
  '/players': typeof PlayersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/team-builder': typeof TeamBuilderRoute
  '/tracker': typeof TrackerRoute
  '/analytics/abilities': typeof AnalyticsAbilitiesRoute
  '/analytics/team-builder': typeof AnalyticsTeamBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/badge-distribution': typeof CommunityBadgeDistributionRoute
  '/community/heatmap': typeof CommunityHeatmapRoute
  '/community/leaderboard': typeof CommunityLeaderboardRoute
  '/deadlockdle/guess-ability': typeof DeadlockdleGuessAbilityRoute
  '/deadlockdle/guess-hero': typeof DeadlockdleGuessHeroRoute
  '/deadlockdle/guess-item': typeof DeadlockdleGuessItemRoute
  '/deadlockdle/guess-sound': typeof DeadlockdleGuessSoundRoute
  '/deadlockdle/item-stats': typeof DeadlockdleItemStatsRoute
  '/deadlockdle/trivia': typeof DeadlockdleTriviaRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/flashcards/heroes': typeof FlashcardsHeroesRoute
  '/flashcards/item-effects': typeof FlashcardsItemEffectsRoute
  '/flashcards/item-upgrades': typeof FlashcardsItemUpgradesRoute
  '/flashcards/items': typeof FlashcardsItemsRoute
  '/heroes/$heroName': typeof HeroesHeroNameRoute
  '/items/$itemName': typeof ItemsItemNameRoute
  '/players/$accountId': typeof PlayersAccountIdRoute
  '/tracker/demo': typeof TrackerDemoRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/community': typeof CommunityIndexRoute
  '/deadlockdle': typeof DeadlockdleIndexRoute
  '/flashcards': typeof FlashcardsIndexRoute
  '/heroes': typeof HeroesIndexRoute
  '/items': typeof ItemsIndexRoute
  '/streamkit': typeof StreamkitIndexRoute
  '/analytics/games/by-rank': typeof AnalyticsGamesByRankRoute
  '/analytics/games/economy': typeof AnalyticsGamesEconomyRoute
  '/analytics/games/over-time': typeof AnalyticsGamesOverTimeRoute
  '/analytics/heroes/$heroName': typeof AnalyticsHeroesHeroNameRoute
  '/analytics/heroes/by-duration': typeof AnalyticsHeroesByDurationRoute
  '/analytics/heroes/by-experience': typeof AnalyticsHeroesByExperienceRoute
  '/analytics/heroes/by-rank': typeof AnalyticsHeroesByRankRoute
  '/analytics/heroes/combos': typeof AnalyticsHeroesCombosRoute
  '/analytics/heroes/matchup-details': typeof AnalyticsHeroesMatchupDetailsRoute
  '/analytics/heroes/matchups': typeof AnalyticsHeroesMatchupsRoute
  '/analytics/heroes/over-time': typeof AnalyticsHeroesOverTimeRoute
  '/analytics/heroes/scoreboard': typeof AnalyticsHeroesScoreboardRoute
  '/analytics/items/$itemName': typeof AnalyticsItemsItemNameRoute
  '/analytics/items/build-flow': typeof AnalyticsItemsBuildFlowRoute
  '/analytics/items/combos': typeof AnalyticsItemsCombosRoute
  '/analytics/items/item-purchase-analysis': typeof AnalyticsItemsItemPurchaseAnalysisRoute
  '/analytics/players/stats-metrics': typeof AnalyticsPlayersStatsMetricsRoute
  '/auth/patreon/callback': typeof AuthPatreonCallbackRoute
  '/games/deadlockdle/guess-ability': typeof GamesDeadlockdleGuessAbilityRoute
  '/games/deadlockdle/guess-hero': typeof GamesDeadlockdleGuessHeroRoute
  '/games/deadlockdle/guess-item': typeof GamesDeadlockdleGuessItemRoute
  '/games/deadlockdle/guess-sound': typeof GamesDeadlockdleGuessSoundRoute
  '/games/deadlockdle/item-stats': typeof GamesDeadlockdleItemStatsRoute
  '/games/deadlockdle/trivia': typeof GamesDeadlockdleTriviaRoute
  '/games/flashcards/heroes': typeof GamesFlashcardsHeroesRoute
  '/games/flashcards/item-effects': typeof GamesFlashcardsItemEffectsRoute
  '/games/flashcards/item-upgrades': typeof GamesFlashcardsItemUpgradesRoute
  '/games/flashcards/items': typeof GamesFlashcardsItemsRoute
  '/tracker/players/$accountId': typeof TrackerPlayersAccountIdRoute
  '/analytics/games': typeof AnalyticsGamesIndexRoute
  '/analytics/heroes': typeof AnalyticsHeroesIndexRoute
  '/analytics/items': typeof AnalyticsItemsIndexRoute
  '/analytics/players': typeof AnalyticsPlayersIndexRoute
  '/games/deadlockdle': typeof GamesDeadlockdleIndexRoute
  '/games/flashcards': typeof GamesFlashcardsIndexRoute
  '/tracker/players': typeof TrackerPlayersIndexRoute
  '/streamkit/widgets/$region/$accountId/$widgetType': typeof StreamkitWidgetsRegionAccountIdWidgetTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abilities': typeof AbilitiesRoute
  '/badge-distribution': typeof BadgeDistributionRoute
  '/data-dumps': typeof DataDumpsRoute
  '/data-privacy': typeof DataPrivacyRoute
  '/deadlockdle': typeof DeadlockdleRouteWithChildren
  '/deadlockstats-privacy': typeof DeadlockstatsPrivacyRoute
  '/flashcards': typeof FlashcardsRouteWithChildren
  '/games': typeof GamesRoute
  '/heatmap': typeof HeatmapRoute
  '/heroes': typeof HeroesRouteWithChildren
  '/ingest-cache': typeof IngestCacheRoute
  '/items': typeof ItemsRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/patron': typeof PatronRoute
  '/players': typeof PlayersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sitemap_index.xml': typeof Sitemap_indexDotxmlRoute
  '/team-builder': typeof TeamBuilderRoute
  '/tracker': typeof TrackerRoute
  '/analytics/abilities': typeof AnalyticsAbilitiesRoute
  '/analytics/games': typeof AnalyticsGamesRouteWithChildren
  '/analytics/heroes': typeof AnalyticsHeroesRouteWithChildren
  '/analytics/items': typeof AnalyticsItemsRouteWithChildren
  '/analytics/players': typeof AnalyticsPlayersRouteWithChildren
  '/analytics/team-builder': typeof AnalyticsTeamBuilderRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/community/badge-distribution': typeof CommunityBadgeDistributionRoute
  '/community/heatmap': typeof CommunityHeatmapRoute
  '/community/leaderboard': typeof CommunityLeaderboardRoute
  '/deadlockdle/guess-ability': typeof DeadlockdleGuessAbilityRoute
  '/deadlockdle/guess-hero': typeof DeadlockdleGuessHeroRoute
  '/deadlockdle/guess-item': typeof DeadlockdleGuessItemRoute
  '/deadlockdle/guess-sound': typeof DeadlockdleGuessSoundRoute
  '/deadlockdle/item-stats': typeof DeadlockdleItemStatsRoute
  '/deadlockdle/trivia': typeof DeadlockdleTriviaRoute
  '/dev/design-system': typeof DevDesignSystemRoute
  '/flashcards/heroes': typeof FlashcardsHeroesRoute
  '/flashcards/item-effects': typeof FlashcardsItemEffectsRoute
  '/flashcards/item-upgrades': typeof FlashcardsItemUpgradesRoute
  '/flashcards/items': typeof FlashcardsItemsRoute
  '/games_/deadlockdle': typeof GamesDeadlockdleRouteWithChildren
  '/games_/flashcards': typeof GamesFlashcardsRouteWithChildren
  '/heroes/$heroName': typeof HeroesHeroNameRoute
  '/items/$itemName': typeof ItemsItemNameRoute
  '/players_/$accountId': typeof PlayersAccountIdRoute
  '/tracker_/demo': typeof TrackerDemoRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/deadlockdle/': typeof DeadlockdleIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/heroes/': typeof HeroesIndexRoute
  '/items/': typeof ItemsIndexRoute
  '/streamkit/': typeof StreamkitIndexRoute
  '/analytics/games/by-rank': typeof AnalyticsGamesByRankRoute
  '/analytics/games/economy': typeof AnalyticsGamesEconomyRoute
  '/analytics/games/over-time': typeof AnalyticsGamesOverTimeRoute
  '/analytics/heroes/$heroName': typeof AnalyticsHeroesHeroNameRoute
  '/analytics/heroes/by-duration': typeof AnalyticsHeroesByDurationRoute
  '/analytics/heroes/by-experience': typeof AnalyticsHeroesByExperienceRoute
  '/analytics/heroes/by-rank': typeof AnalyticsHeroesByRankRoute
  '/analytics/heroes/combos': typeof AnalyticsHeroesCombosRoute
  '/analytics/heroes/matchup-details': typeof AnalyticsHeroesMatchupDetailsRoute
  '/analytics/heroes/matchups': typeof AnalyticsHeroesMatchupsRoute
  '/analytics/heroes/over-time': typeof AnalyticsHeroesOverTimeRoute
  '/analytics/heroes/scoreboard': typeof AnalyticsHeroesScoreboardRoute
  '/analytics/items/$itemName': typeof AnalyticsItemsItemNameRoute
  '/analytics/items/build-flow': typeof AnalyticsItemsBuildFlowRoute
  '/analytics/items/combos': typeof AnalyticsItemsCombosRoute
  '/analytics/items/item-purchase-analysis': typeof AnalyticsItemsItemPurchaseAnalysisRoute
  '/analytics/players/stats-metrics': typeof AnalyticsPlayersStatsMetricsRoute
  '/auth/patreon/callback': typeof AuthPatreonCallbackRoute
  '/games_/deadlockdle/guess-ability': typeof GamesDeadlockdleGuessAbilityRoute
  '/games_/deadlockdle/guess-hero': typeof GamesDeadlockdleGuessHeroRoute
  '/games_/deadlockdle/guess-item': typeof GamesDeadlockdleGuessItemRoute
  '/games_/deadlockdle/guess-sound': typeof GamesDeadlockdleGuessSoundRoute
  '/games_/deadlockdle/item-stats': typeof GamesDeadlockdleItemStatsRoute
  '/games_/deadlockdle/trivia': typeof GamesDeadlockdleTriviaRoute
  '/games_/flashcards/heroes': typeof GamesFlashcardsHeroesRoute
  '/games_/flashcards/item-effects': typeof GamesFlashcardsItemEffectsRoute
  '/games_/flashcards/item-upgrades': typeof GamesFlashcardsItemUpgradesRoute
  '/games_/flashcards/items': typeof GamesFlashcardsItemsRoute
  '/tracker_/players/$accountId': typeof TrackerPlayersAccountIdRoute
  '/analytics/games/': typeof AnalyticsGamesIndexRoute
  '/analytics/heroes/': typeof AnalyticsHeroesIndexRoute
  '/analytics/items/': typeof AnalyticsItemsIndexRoute
  '/analytics/players/': typeof AnalyticsPlayersIndexRoute
  '/games_/deadlockdle/': typeof GamesDeadlockdleIndexRoute
  '/games_/flashcards/': typeof GamesFlashcardsIndexRoute
  '/tracker_/players/': typeof TrackerPlayersIndexRoute
  '/streamkit/widgets/$region/$accountId/$widgetType': typeof StreamkitWidgetsRegionAccountIdWidgetTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abilities'
    | '/badge-distribution'
    | '/data-dumps'
    | '/data-privacy'
    | '/deadlockdle'
    | '/deadlockstats-privacy'
    | '/flashcards'
    | '/games'
    | '/heatmap'
    | '/heroes'
    | '/ingest-cache'
    | '/items'
    | '/leaderboard'
    | '/patron'
    | '/players'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/team-builder'
    | '/tracker'
    | '/analytics/abilities'
    | '/analytics/games'
    | '/analytics/heroes'
    | '/analytics/items'
    | '/analytics/players'
    | '/analytics/team-builder'
    | '/blog/$slug'
    | '/community/badge-distribution'
    | '/community/heatmap'
    | '/community/leaderboard'
    | '/deadlockdle/guess-ability'
    | '/deadlockdle/guess-hero'
    | '/deadlockdle/guess-item'
    | '/deadlockdle/guess-sound'
    | '/deadlockdle/item-stats'
    | '/deadlockdle/trivia'
    | '/dev/design-system'
    | '/flashcards/heroes'
    | '/flashcards/item-effects'
    | '/flashcards/item-upgrades'
    | '/flashcards/items'
    | '/games/deadlockdle'
    | '/games/flashcards'
    | '/heroes/$heroName'
    | '/items/$itemName'
    | '/players/$accountId'
    | '/tracker/demo'
    | '/analytics/'
    | '/blog/'
    | '/community/'
    | '/deadlockdle/'
    | '/flashcards/'
    | '/heroes/'
    | '/items/'
    | '/streamkit/'
    | '/analytics/games/by-rank'
    | '/analytics/games/economy'
    | '/analytics/games/over-time'
    | '/analytics/heroes/$heroName'
    | '/analytics/heroes/by-duration'
    | '/analytics/heroes/by-experience'
    | '/analytics/heroes/by-rank'
    | '/analytics/heroes/combos'
    | '/analytics/heroes/matchup-details'
    | '/analytics/heroes/matchups'
    | '/analytics/heroes/over-time'
    | '/analytics/heroes/scoreboard'
    | '/analytics/items/$itemName'
    | '/analytics/items/build-flow'
    | '/analytics/items/combos'
    | '/analytics/items/item-purchase-analysis'
    | '/analytics/players/stats-metrics'
    | '/auth/patreon/callback'
    | '/games/deadlockdle/guess-ability'
    | '/games/deadlockdle/guess-hero'
    | '/games/deadlockdle/guess-item'
    | '/games/deadlockdle/guess-sound'
    | '/games/deadlockdle/item-stats'
    | '/games/deadlockdle/trivia'
    | '/games/flashcards/heroes'
    | '/games/flashcards/item-effects'
    | '/games/flashcards/item-upgrades'
    | '/games/flashcards/items'
    | '/tracker/players/$accountId'
    | '/analytics/games/'
    | '/analytics/heroes/'
    | '/analytics/items/'
    | '/analytics/players/'
    | '/games/deadlockdle/'
    | '/games/flashcards/'
    | '/tracker/players/'
    | '/streamkit/widgets/$region/$accountId/$widgetType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abilities'
    | '/badge-distribution'
    | '/data-dumps'
    | '/data-privacy'
    | '/deadlockstats-privacy'
    | '/games'
    | '/heatmap'
    | '/ingest-cache'
    | '/leaderboard'
    | '/patron'
    | '/players'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/team-builder'
    | '/tracker'
    | '/analytics/abilities'
    | '/analytics/team-builder'
    | '/blog/$slug'
    | '/community/badge-distribution'
    | '/community/heatmap'
    | '/community/leaderboard'
    | '/deadlockdle/guess-ability'
    | '/deadlockdle/guess-hero'
    | '/deadlockdle/guess-item'
    | '/deadlockdle/guess-sound'
    | '/deadlockdle/item-stats'
    | '/deadlockdle/trivia'
    | '/dev/design-system'
    | '/flashcards/heroes'
    | '/flashcards/item-effects'
    | '/flashcards/item-upgrades'
    | '/flashcards/items'
    | '/heroes/$heroName'
    | '/items/$itemName'
    | '/players/$accountId'
    | '/tracker/demo'
    | '/analytics'
    | '/blog'
    | '/community'
    | '/deadlockdle'
    | '/flashcards'
    | '/heroes'
    | '/items'
    | '/streamkit'
    | '/analytics/games/by-rank'
    | '/analytics/games/economy'
    | '/analytics/games/over-time'
    | '/analytics/heroes/$heroName'
    | '/analytics/heroes/by-duration'
    | '/analytics/heroes/by-experience'
    | '/analytics/heroes/by-rank'
    | '/analytics/heroes/combos'
    | '/analytics/heroes/matchup-details'
    | '/analytics/heroes/matchups'
    | '/analytics/heroes/over-time'
    | '/analytics/heroes/scoreboard'
    | '/analytics/items/$itemName'
    | '/analytics/items/build-flow'
    | '/analytics/items/combos'
    | '/analytics/items/item-purchase-analysis'
    | '/analytics/players/stats-metrics'
    | '/auth/patreon/callback'
    | '/games/deadlockdle/guess-ability'
    | '/games/deadlockdle/guess-hero'
    | '/games/deadlockdle/guess-item'
    | '/games/deadlockdle/guess-sound'
    | '/games/deadlockdle/item-stats'
    | '/games/deadlockdle/trivia'
    | '/games/flashcards/heroes'
    | '/games/flashcards/item-effects'
    | '/games/flashcards/item-upgrades'
    | '/games/flashcards/items'
    | '/tracker/players/$accountId'
    | '/analytics/games'
    | '/analytics/heroes'
    | '/analytics/items'
    | '/analytics/players'
    | '/games/deadlockdle'
    | '/games/flashcards'
    | '/tracker/players'
    | '/streamkit/widgets/$region/$accountId/$widgetType'
  id:
    | '__root__'
    | '/'
    | '/abilities'
    | '/badge-distribution'
    | '/data-dumps'
    | '/data-privacy'
    | '/deadlockdle'
    | '/deadlockstats-privacy'
    | '/flashcards'
    | '/games'
    | '/heatmap'
    | '/heroes'
    | '/ingest-cache'
    | '/items'
    | '/leaderboard'
    | '/patron'
    | '/players'
    | '/sitemap.xml'
    | '/sitemap_index.xml'
    | '/team-builder'
    | '/tracker'
    | '/analytics/abilities'
    | '/analytics/games'
    | '/analytics/heroes'
    | '/analytics/items'
    | '/analytics/players'
    | '/analytics/team-builder'
    | '/blog/$slug'
    | '/community/badge-distribution'
    | '/community/heatmap'
    | '/community/leaderboard'
    | '/deadlockdle/guess-ability'
    | '/deadlockdle/guess-hero'
    | '/deadlockdle/guess-item'
    | '/deadlockdle/guess-sound'
    | '/deadlockdle/item-stats'
    | '/deadlockdle/trivia'
    | '/dev/design-system'
    | '/flashcards/heroes'
    | '/flashcards/item-effects'
    | '/flashcards/item-upgrades'
    | '/flashcards/items'
    | '/games_/deadlockdle'
    | '/games_/flashcards'
    | '/heroes/$heroName'
    | '/items/$itemName'
    | '/players_/$accountId'
    | '/tracker_/demo'
    | '/analytics/'
    | '/blog/'
    | '/community/'
    | '/deadlockdle/'
    | '/flashcards/'
    | '/heroes/'
    | '/items/'
    | '/streamkit/'
    | '/analytics/games/by-rank'
    | '/analytics/games/economy'
    | '/analytics/games/over-time'
    | '/analytics/heroes/$heroName'
    | '/analytics/heroes/by-duration'
    | '/analytics/heroes/by-experience'
    | '/analytics/heroes/by-rank'
    | '/analytics/heroes/combos'
    | '/analytics/heroes/matchup-details'
    | '/analytics/heroes/matchups'
    | '/analytics/heroes/over-time'
    | '/analytics/heroes/scoreboard'
    | '/analytics/items/$itemName'
    | '/analytics/items/build-flow'
    | '/analytics/items/combos'
    | '/analytics/items/item-purchase-analysis'
    | '/analytics/players/stats-metrics'
    | '/auth/patreon/callback'
    | '/games_/deadlockdle/guess-ability'
    | '/games_/deadlockdle/guess-hero'
    | '/games_/deadlockdle/guess-item'
    | '/games_/deadlockdle/guess-sound'
    | '/games_/deadlockdle/item-stats'
    | '/games_/deadlockdle/trivia'
    | '/games_/flashcards/heroes'
    | '/games_/flashcards/item-effects'
    | '/games_/flashcards/item-upgrades'
    | '/games_/flashcards/items'
    | '/tracker_/players/$accountId'
    | '/analytics/games/'
    | '/analytics/heroes/'
    | '/analytics/items/'
    | '/analytics/players/'
    | '/games_/deadlockdle/'
    | '/games_/flashcards/'
    | '/tracker_/players/'
    | '/streamkit/widgets/$region/$accountId/$widgetType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbilitiesRoute: typeof AbilitiesRoute
  BadgeDistributionRoute: typeof BadgeDistributionRoute
  DataDumpsRoute: typeof DataDumpsRoute
  DataPrivacyRoute: typeof DataPrivacyRoute
  DeadlockdleRoute: typeof DeadlockdleRouteWithChildren
  DeadlockstatsPrivacyRoute: typeof DeadlockstatsPrivacyRoute
  FlashcardsRoute: typeof FlashcardsRouteWithChildren
  GamesRoute: typeof GamesRoute
  HeatmapRoute: typeof HeatmapRoute
  HeroesRoute: typeof HeroesRouteWithChildren
  IngestCacheRoute: typeof IngestCacheRoute
  ItemsRoute: typeof ItemsRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  PatronRoute: typeof PatronRoute
  PlayersRoute: typeof PlayersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Sitemap_indexDotxmlRoute: typeof Sitemap_indexDotxmlRoute
  TeamBuilderRoute: typeof TeamBuilderRoute
  TrackerRoute: typeof TrackerRoute
  AnalyticsAbilitiesRoute: typeof AnalyticsAbilitiesRoute
  AnalyticsGamesRoute: typeof AnalyticsGamesRouteWithChildren
  AnalyticsHeroesRoute: typeof AnalyticsHeroesRouteWithChildren
  AnalyticsItemsRoute: typeof AnalyticsItemsRouteWithChildren
  AnalyticsPlayersRoute: typeof AnalyticsPlayersRouteWithChildren
  AnalyticsTeamBuilderRoute: typeof AnalyticsTeamBuilderRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CommunityBadgeDistributionRoute: typeof CommunityBadgeDistributionRoute
  CommunityHeatmapRoute: typeof CommunityHeatmapRoute
  CommunityLeaderboardRoute: typeof CommunityLeaderboardRoute
  DevDesignSystemRoute: typeof DevDesignSystemRoute
  GamesDeadlockdleRoute: typeof GamesDeadlockdleRouteWithChildren
  GamesFlashcardsRoute: typeof GamesFlashcardsRouteWithChildren
  PlayersAccountIdRoute: typeof PlayersAccountIdRoute
  TrackerDemoRoute: typeof TrackerDemoRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  StreamkitIndexRoute: typeof StreamkitIndexRoute
  AuthPatreonCallbackRoute: typeof AuthPatreonCallbackRoute
  TrackerPlayersAccountIdRoute: typeof TrackerPlayersAccountIdRoute
  TrackerPlayersIndexRoute: typeof TrackerPlayersIndexRoute
  StreamkitWidgetsRegionAccountIdWidgetTypeRoute: typeof StreamkitWidgetsRegionAccountIdWidgetTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abilities': {
      id: '/abilities'
      path: '/abilities'
      fullPath: '/abilities'
      preLoaderRoute: typeof AbilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge-distribution': {
      id: '/badge-distribution'
      path: '/badge-distribution'
      fullPath: '/badge-distribution'
      preLoaderRoute: typeof BadgeDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-dumps': {
      id: '/data-dumps'
      path: '/data-dumps'
      fullPath: '/data-dumps'
      preLoaderRoute: typeof DataDumpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-privacy': {
      id: '/data-privacy'
      path: '/data-privacy'
      fullPath: '/data-privacy'
      preLoaderRoute: typeof DataPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlockdle': {
      id: '/deadlockdle'
      path: '/deadlockdle'
      fullPath: '/deadlockdle'
      preLoaderRoute: typeof DeadlockdleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlockstats-privacy': {
      id: '/deadlockstats-privacy'
      path: '/deadlockstats-privacy'
      fullPath: '/deadlockstats-privacy'
      preLoaderRoute: typeof DeadlockstatsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes': {
      id: '/heroes'
      path: '/heroes'
      fullPath: '/heroes'
      preLoaderRoute: typeof HeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingest-cache': {
      id: '/ingest-cache'
      path: '/ingest-cache'
      fullPath: '/ingest-cache'
      preLoaderRoute: typeof IngestCacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patron': {
      id: '/patron'
      path: '/patron'
      fullPath: '/patron'
      preLoaderRoute: typeof PatronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap_index.xml': {
      id: '/sitemap_index.xml'
      path: '/sitemap_index.xml'
      fullPath: '/sitemap_index.xml'
      preLoaderRoute: typeof Sitemap_indexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-builder': {
      id: '/team-builder'
      path: '/team-builder'
      fullPath: '/team-builder'
      preLoaderRoute: typeof TeamBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/abilities': {
      id: '/analytics/abilities'
      path: '/analytics/abilities'
      fullPath: '/analytics/abilities'
      preLoaderRoute: typeof AnalyticsAbilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/games': {
      id: '/analytics/games'
      path: '/analytics/games'
      fullPath: '/analytics/games'
      preLoaderRoute: typeof AnalyticsGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/heroes': {
      id: '/analytics/heroes'
      path: '/analytics/heroes'
      fullPath: '/analytics/heroes'
      preLoaderRoute: typeof AnalyticsHeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/items': {
      id: '/analytics/items'
      path: '/analytics/items'
      fullPath: '/analytics/items'
      preLoaderRoute: typeof AnalyticsItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/players': {
      id: '/analytics/players'
      path: '/analytics/players'
      fullPath: '/analytics/players'
      preLoaderRoute: typeof AnalyticsPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/team-builder': {
      id: '/analytics/team-builder'
      path: '/analytics/team-builder'
      fullPath: '/analytics/team-builder'
      preLoaderRoute: typeof AnalyticsTeamBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/badge-distribution': {
      id: '/community/badge-distribution'
      path: '/community/badge-distribution'
      fullPath: '/community/badge-distribution'
      preLoaderRoute: typeof CommunityBadgeDistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/heatmap': {
      id: '/community/heatmap'
      path: '/community/heatmap'
      fullPath: '/community/heatmap'
      preLoaderRoute: typeof CommunityHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/leaderboard': {
      id: '/community/leaderboard'
      path: '/community/leaderboard'
      fullPath: '/community/leaderboard'
      preLoaderRoute: typeof CommunityLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deadlockdle/': {
      id: '/deadlockdle/'
      path: '/'
      fullPath: '/deadlockdle/'
      preLoaderRoute: typeof DeadlockdleIndexRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/guess-ability': {
      id: '/deadlockdle/guess-ability'
      path: '/guess-ability'
      fullPath: '/deadlockdle/guess-ability'
      preLoaderRoute: typeof DeadlockdleGuessAbilityRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/guess-hero': {
      id: '/deadlockdle/guess-hero'
      path: '/guess-hero'
      fullPath: '/deadlockdle/guess-hero'
      preLoaderRoute: typeof DeadlockdleGuessHeroRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/guess-item': {
      id: '/deadlockdle/guess-item'
      path: '/guess-item'
      fullPath: '/deadlockdle/guess-item'
      preLoaderRoute: typeof DeadlockdleGuessItemRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/guess-sound': {
      id: '/deadlockdle/guess-sound'
      path: '/guess-sound'
      fullPath: '/deadlockdle/guess-sound'
      preLoaderRoute: typeof DeadlockdleGuessSoundRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/item-stats': {
      id: '/deadlockdle/item-stats'
      path: '/item-stats'
      fullPath: '/deadlockdle/item-stats'
      preLoaderRoute: typeof DeadlockdleItemStatsRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/deadlockdle/trivia': {
      id: '/deadlockdle/trivia'
      path: '/trivia'
      fullPath: '/deadlockdle/trivia'
      preLoaderRoute: typeof DeadlockdleTriviaRouteImport
      parentRoute: typeof DeadlockdleRoute
    }
    '/dev/design-system': {
      id: '/dev/design-system'
      path: '/dev/design-system'
      fullPath: '/dev/design-system'
      preLoaderRoute: typeof DevDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/': {
      id: '/flashcards/'
      path: '/'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof FlashcardsIndexRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/flashcards/heroes': {
      id: '/flashcards/heroes'
      path: '/heroes'
      fullPath: '/flashcards/heroes'
      preLoaderRoute: typeof FlashcardsHeroesRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/flashcards/item-effects': {
      id: '/flashcards/item-effects'
      path: '/item-effects'
      fullPath: '/flashcards/item-effects'
      preLoaderRoute: typeof FlashcardsItemEffectsRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/flashcards/item-upgrades': {
      id: '/flashcards/item-upgrades'
      path: '/item-upgrades'
      fullPath: '/flashcards/item-upgrades'
      preLoaderRoute: typeof FlashcardsItemUpgradesRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/flashcards/items': {
      id: '/flashcards/items'
      path: '/items'
      fullPath: '/flashcards/items'
      preLoaderRoute: typeof FlashcardsItemsRouteImport
      parentRoute: typeof FlashcardsRoute
    }
    '/games_/deadlockdle': {
      id: '/games_/deadlockdle'
      path: '/games/deadlockdle'
      fullPath: '/games/deadlockdle'
      preLoaderRoute: typeof GamesDeadlockdleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/flashcards': {
      id: '/games_/flashcards'
      path: '/games/flashcards'
      fullPath: '/games/flashcards'
      preLoaderRoute: typeof GamesFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes/': {
      id: '/heroes/'
      path: '/'
      fullPath: '/heroes/'
      preLoaderRoute: typeof HeroesIndexRouteImport
      parentRoute: typeof HeroesRoute
    }
    '/heroes/$heroName': {
      id: '/heroes/$heroName'
      path: '/$heroName'
      fullPath: '/heroes/$heroName'
      preLoaderRoute: typeof HeroesHeroNameRouteImport
      parentRoute: typeof HeroesRoute
    }
    '/items/': {
      id: '/items/'
      path: '/'
      fullPath: '/items/'
      preLoaderRoute: typeof ItemsIndexRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/items/$itemName': {
      id: '/items/$itemName'
      path: '/$itemName'
      fullPath: '/items/$itemName'
      preLoaderRoute: typeof ItemsItemNameRouteImport
      parentRoute: typeof ItemsRoute
    }
    '/players_/$accountId': {
      id: '/players_/$accountId'
      path: '/players/$accountId'
      fullPath: '/players/$accountId'
      preLoaderRoute: typeof PlayersAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamkit/': {
      id: '/streamkit/'
      path: '/streamkit'
      fullPath: '/streamkit/'
      preLoaderRoute: typeof StreamkitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker_/demo': {
      id: '/tracker_/demo'
      path: '/tracker/demo'
      fullPath: '/tracker/demo'
      preLoaderRoute: typeof TrackerDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/games/': {
      id: '/analytics/games/'
      path: '/'
      fullPath: '/analytics/games/'
      preLoaderRoute: typeof AnalyticsGamesIndexRouteImport
      parentRoute: typeof AnalyticsGamesRoute
    }
    '/analytics/games/by-rank': {
      id: '/analytics/games/by-rank'
      path: '/by-rank'
      fullPath: '/analytics/games/by-rank'
      preLoaderRoute: typeof AnalyticsGamesByRankRouteImport
      parentRoute: typeof AnalyticsGamesRoute
    }
    '/analytics/games/economy': {
      id: '/analytics/games/economy'
      path: '/economy'
      fullPath: '/analytics/games/economy'
      preLoaderRoute: typeof AnalyticsGamesEconomyRouteImport
      parentRoute: typeof AnalyticsGamesRoute
    }
    '/analytics/games/over-time': {
      id: '/analytics/games/over-time'
      path: '/over-time'
      fullPath: '/analytics/games/over-time'
      preLoaderRoute: typeof AnalyticsGamesOverTimeRouteImport
      parentRoute: typeof AnalyticsGamesRoute
    }
    '/analytics/heroes/': {
      id: '/analytics/heroes/'
      path: '/'
      fullPath: '/analytics/heroes/'
      preLoaderRoute: typeof AnalyticsHeroesIndexRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/heroes/$heroName': {
      id: '/analytics/heroes/$heroName'
      path: '/$heroName'
      fullPath: '/analytics/heroes/$heroName'
      preLoaderRoute: typeof AnalyticsHeroesHeroNameRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/heroes/by-duration': {
      id: '/analytics/heroes/by-duration'
      path: '/by-duration'
      fullPath: '/analytics/heroes/by-duration'
      preLoaderRoute: typeof AnalyticsHeroesByDurationRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/heroes/by-experience': {
      id: '/analytics/heroes/by-experience'
      path: '/by-experience'
      fullPath: '/analytics/heroes/by-experience'
      preLoaderRoute: typeof AnalyticsHeroesByExperienceRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/heroes/by-rank': {
      id: '/analytics/heroes/by-rank'
      path: '/by-rank'
      fullPath: '/analytics/heroes/by-rank'
      preLoaderRoute: typeof AnalyticsHeroesByRankRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/heroes/combos': {
      id: '/analytics/heroes/combos'
      path: '/combos'
      fullPath: '/analytics/heroes/combos'
      preLoaderRoute: typeof AnalyticsHeroesCombosRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/heroes/matchup-details': {
      id: '/analytics/heroes/matchup-details'
      path: '/matchup-details'
      fullPath: '/analytics/heroes/matchup-details'
      preLoaderRoute: typeof AnalyticsHeroesMatchupDetailsRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/heroes/matchups': {
      id: '/analytics/heroes/matchups'
      path: '/matchups'
      fullPath: '/analytics/heroes/matchups'
      preLoaderRoute: typeof AnalyticsHeroesMatchupsRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/heroes/over-time': {
      id: '/analytics/heroes/over-time'
      path: '/over-time'
      fullPath: '/analytics/heroes/over-time'
      preLoaderRoute: typeof AnalyticsHeroesOverTimeRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/heroes/scoreboard': {
      id: '/analytics/heroes/scoreboard'
      path: '/scoreboard'
      fullPath: '/analytics/heroes/scoreboard'
      preLoaderRoute: typeof AnalyticsHeroesScoreboardRouteImport
      parentRoute: typeof AnalyticsHeroesRoute
    }
    '/analytics/items/': {
      id: '/analytics/items/'
      path: '/'
      fullPath: '/analytics/items/'
      preLoaderRoute: typeof AnalyticsItemsIndexRouteImport
      parentRoute: typeof AnalyticsItemsRoute
    }
    '/analytics/items/$itemName': {
      id: '/analytics/items/$itemName'
      path: '/$itemName'
      fullPath: '/analytics/items/$itemName'
      preLoaderRoute: typeof AnalyticsItemsItemNameRouteImport
      parentRoute: typeof AnalyticsItemsRoute
    }
    '/analytics/items/build-flow': {
      id: '/analytics/items/build-flow'
      path: '/build-flow'
      fullPath: '/analytics/items/build-flow'
      preLoaderRoute: typeof AnalyticsItemsBuildFlowRouteImport
      parentRoute: typeof AnalyticsItemsRoute
    }
    '/analytics/items/combos': {
      id: '/analytics/items/combos'
      path: '/combos'
      fullPath: '/analytics/items/combos'
      preLoaderRoute: typeof AnalyticsItemsCombosRouteImport
      parentRoute: typeof AnalyticsItemsRoute
    }
    '/analytics/items/item-purchase-analysis': {
      id: '/analytics/items/item-purchase-analysis'
      path: '/item-purchase-analysis'
      fullPath: '/analytics/items/item-purchase-analysis'
      preLoaderRoute: typeof AnalyticsItemsItemPurchaseAnalysisRouteImport
      parentRoute: typeof AnalyticsItemsRoute
    }
    '/analytics/players/': {
      id: '/analytics/players/'
      path: '/'
      fullPath: '/analytics/players/'
      preLoaderRoute: typeof AnalyticsPlayersIndexRouteImport
      parentRoute: typeof AnalyticsPlayersRoute
    }
    '/analytics/players/stats-metrics': {
      id: '/analytics/players/stats-metrics'
      path: '/stats-metrics'
      fullPath: '/analytics/players/stats-metrics'
      preLoaderRoute: typeof AnalyticsPlayersStatsMetricsRouteImport
      parentRoute: typeof AnalyticsPlayersRoute
    }
    '/auth/patreon/callback': {
      id: '/auth/patreon/callback'
      path: '/auth/patreon/callback'
      fullPath: '/auth/patreon/callback'
      preLoaderRoute: typeof AuthPatreonCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games_/deadlockdle/': {
      id: '/games_/deadlockdle/'
      path: '/'
      fullPath: '/games/deadlockdle/'
      preLoaderRoute: typeof GamesDeadlockdleIndexRouteImport
      parentRoute: typeof GamesDeadlockdleRoute
    }
    '/games_/deadlockdle/guess-ability': {
      id: '/games_/deadlockdle/guess-ability'
      path: '/guess-ability'
      fullPath: '/games/deadlockdle/guess-ability'
      preLoaderRoute: typeof GamesDeadlockdleGuessAbilityRouteImport
      parentRoute: typeof GamesDeadlockdleRoute
    }
    '/games_/deadlockdle/guess-hero': {
      id: '/games_/deadlockdle/guess-hero'
      path: '/guess-hero'
      fullPath: '/games/deadlockdle/guess-hero'
      preLoaderRoute: typeof GamesDeadlockdleGuessHeroRouteImport
      parentRoute: typeof GamesDeadlockdleRoute
    }
    '/games_/deadlockdle/guess-item': {
      id: '/games_/deadlockdle/guess-item'
      path: '/guess-item'
      fullPath: '/games/deadlockdle/guess-item'
      preLoaderRoute: typeof GamesDeadlockdleGuessItemRouteImport
      parentRoute: typeof GamesDeadlockdleRoute
    }
    '/games_/deadlockdle/guess-sound': {
      id: '/games_/deadlockdle/guess-sound'
      path: '/guess-sound'
      fullPath: '/games/deadlockdle/guess-sound'
      preLoaderRoute: typeof GamesDeadlockdleGuessSoundRouteImport
      parentRoute: typeof GamesDeadlockdleRoute
    }
    '/games_/deadlockdle/item-stats': {
      id: '/games_/deadlockdle/item-stats'
      path: '/item-stats'
      fullPath: '/games/deadlockdle/item-stats'
      preLoaderRoute: typeof GamesDeadlockdleItemStatsRouteImport
      parentRoute: typeof GamesDeadlockdleRoute
    }
    '/games_/deadlockdle/trivia': {
      id: '/games_/deadlockdle/trivia'
      path: '/trivia'
      fullPath: '/games/deadlockdle/trivia'
      preLoaderRoute: typeof GamesDeadlockdleTriviaRouteImport
      parentRoute: typeof GamesDeadlockdleRoute
    }
    '/games_/flashcards/': {
      id: '/games_/flashcards/'
      path: '/'
      fullPath: '/games/flashcards/'
      preLoaderRoute: typeof GamesFlashcardsIndexRouteImport
      parentRoute: typeof GamesFlashcardsRoute
    }
    '/games_/flashcards/heroes': {
      id: '/games_/flashcards/heroes'
      path: '/heroes'
      fullPath: '/games/flashcards/heroes'
      preLoaderRoute: typeof GamesFlashcardsHeroesRouteImport
      parentRoute: typeof GamesFlashcardsRoute
    }
    '/games_/flashcards/item-effects': {
      id: '/games_/flashcards/item-effects'
      path: '/item-effects'
      fullPath: '/games/flashcards/item-effects'
      preLoaderRoute: typeof GamesFlashcardsItemEffectsRouteImport
      parentRoute: typeof GamesFlashcardsRoute
    }
    '/games_/flashcards/item-upgrades': {
      id: '/games_/flashcards/item-upgrades'
      path: '/item-upgrades'
      fullPath: '/games/flashcards/item-upgrades'
      preLoaderRoute: typeof GamesFlashcardsItemUpgradesRouteImport
      parentRoute: typeof GamesFlashcardsRoute
    }
    '/games_/flashcards/items': {
      id: '/games_/flashcards/items'
      path: '/items'
      fullPath: '/games/flashcards/items'
      preLoaderRoute: typeof GamesFlashcardsItemsRouteImport
      parentRoute: typeof GamesFlashcardsRoute
    }
    '/tracker_/players/': {
      id: '/tracker_/players/'
      path: '/tracker/players'
      fullPath: '/tracker/players/'
      preLoaderRoute: typeof TrackerPlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker_/players/$accountId': {
      id: '/tracker_/players/$accountId'
      path: '/tracker/players/$accountId'
      fullPath: '/tracker/players/$accountId'
      preLoaderRoute: typeof TrackerPlayersAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamkit/widgets/$region/$accountId/$widgetType': {
      id: '/streamkit/widgets/$region/$accountId/$widgetType'
      path: '/streamkit/widgets/$region/$accountId/$widgetType'
      fullPath: '/streamkit/widgets/$region/$accountId/$widgetType'
      preLoaderRoute: typeof StreamkitWidgetsRegionAccountIdWidgetTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeadlockdleRouteChildren {
  DeadlockdleGuessAbilityRoute: typeof DeadlockdleGuessAbilityRoute
  DeadlockdleGuessHeroRoute: typeof DeadlockdleGuessHeroRoute
  DeadlockdleGuessItemRoute: typeof DeadlockdleGuessItemRoute
  DeadlockdleGuessSoundRoute: typeof DeadlockdleGuessSoundRoute
  DeadlockdleItemStatsRoute: typeof DeadlockdleItemStatsRoute
  DeadlockdleTriviaRoute: typeof DeadlockdleTriviaRoute
  DeadlockdleIndexRoute: typeof DeadlockdleIndexRoute
}

const DeadlockdleRouteChildren: DeadlockdleRouteChildren = {
  DeadlockdleGuessAbilityRoute: DeadlockdleGuessAbilityRoute,
  DeadlockdleGuessHeroRoute: DeadlockdleGuessHeroRoute,
  DeadlockdleGuessItemRoute: DeadlockdleGuessItemRoute,
  DeadlockdleGuessSoundRoute: DeadlockdleGuessSoundRoute,
  DeadlockdleItemStatsRoute: DeadlockdleItemStatsRoute,
  DeadlockdleTriviaRoute: DeadlockdleTriviaRoute,
  DeadlockdleIndexRoute: DeadlockdleIndexRoute,
}

const DeadlockdleRouteWithChildren = DeadlockdleRoute._addFileChildren(
  DeadlockdleRouteChildren,
)

interface FlashcardsRouteChildren {
  FlashcardsHeroesRoute: typeof FlashcardsHeroesRoute
  FlashcardsItemEffectsRoute: typeof FlashcardsItemEffectsRoute
  FlashcardsItemUpgradesRoute: typeof FlashcardsItemUpgradesRoute
  FlashcardsItemsRoute: typeof FlashcardsItemsRoute
  FlashcardsIndexRoute: typeof FlashcardsIndexRoute
}

const FlashcardsRouteChildren: FlashcardsRouteChildren = {
  FlashcardsHeroesRoute: FlashcardsHeroesRoute,
  FlashcardsItemEffectsRoute: FlashcardsItemEffectsRoute,
  FlashcardsItemUpgradesRoute: FlashcardsItemUpgradesRoute,
  FlashcardsItemsRoute: FlashcardsItemsRoute,
  FlashcardsIndexRoute: FlashcardsIndexRoute,
}

const FlashcardsRouteWithChildren = FlashcardsRoute._addFileChildren(
  FlashcardsRouteChildren,
)

interface HeroesRouteChildren {
  HeroesHeroNameRoute: typeof HeroesHeroNameRoute
  HeroesIndexRoute: typeof HeroesIndexRoute
}

const HeroesRouteChildren: HeroesRouteChildren = {
  HeroesHeroNameRoute: HeroesHeroNameRoute,
  HeroesIndexRoute: HeroesIndexRoute,
}

const HeroesRouteWithChildren =
  HeroesRoute._addFileChildren(HeroesRouteChildren)

interface ItemsRouteChildren {
  ItemsItemNameRoute: typeof ItemsItemNameRoute
  ItemsIndexRoute: typeof ItemsIndexRoute
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsItemNameRoute: ItemsItemNameRoute,
  ItemsIndexRoute: ItemsIndexRoute,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

interface AnalyticsGamesRouteChildren {
  AnalyticsGamesByRankRoute: typeof AnalyticsGamesByRankRoute
  AnalyticsGamesEconomyRoute: typeof AnalyticsGamesEconomyRoute
  AnalyticsGamesOverTimeRoute: typeof AnalyticsGamesOverTimeRoute
  AnalyticsGamesIndexRoute: typeof AnalyticsGamesIndexRoute
}

const AnalyticsGamesRouteChildren: AnalyticsGamesRouteChildren = {
  AnalyticsGamesByRankRoute: AnalyticsGamesByRankRoute,
  AnalyticsGamesEconomyRoute: AnalyticsGamesEconomyRoute,
  AnalyticsGamesOverTimeRoute: AnalyticsGamesOverTimeRoute,
  AnalyticsGamesIndexRoute: AnalyticsGamesIndexRoute,
}

const AnalyticsGamesRouteWithChildren = AnalyticsGamesRoute._addFileChildren(
  AnalyticsGamesRouteChildren,
)

interface AnalyticsHeroesRouteChildren {
  AnalyticsHeroesHeroNameRoute: typeof AnalyticsHeroesHeroNameRoute
  AnalyticsHeroesByDurationRoute: typeof AnalyticsHeroesByDurationRoute
  AnalyticsHeroesByExperienceRoute: typeof AnalyticsHeroesByExperienceRoute
  AnalyticsHeroesByRankRoute: typeof AnalyticsHeroesByRankRoute
  AnalyticsHeroesCombosRoute: typeof AnalyticsHeroesCombosRoute
  AnalyticsHeroesMatchupDetailsRoute: typeof AnalyticsHeroesMatchupDetailsRoute
  AnalyticsHeroesMatchupsRoute: typeof AnalyticsHeroesMatchupsRoute
  AnalyticsHeroesOverTimeRoute: typeof AnalyticsHeroesOverTimeRoute
  AnalyticsHeroesScoreboardRoute: typeof AnalyticsHeroesScoreboardRoute
  AnalyticsHeroesIndexRoute: typeof AnalyticsHeroesIndexRoute
}

const AnalyticsHeroesRouteChildren: AnalyticsHeroesRouteChildren = {
  AnalyticsHeroesHeroNameRoute: AnalyticsHeroesHeroNameRoute,
  AnalyticsHeroesByDurationRoute: AnalyticsHeroesByDurationRoute,
  AnalyticsHeroesByExperienceRoute: AnalyticsHeroesByExperienceRoute,
  AnalyticsHeroesByRankRoute: AnalyticsHeroesByRankRoute,
  AnalyticsHeroesCombosRoute: AnalyticsHeroesCombosRoute,
  AnalyticsHeroesMatchupDetailsRoute: AnalyticsHeroesMatchupDetailsRoute,
  AnalyticsHeroesMatchupsRoute: AnalyticsHeroesMatchupsRoute,
  AnalyticsHeroesOverTimeRoute: AnalyticsHeroesOverTimeRoute,
  AnalyticsHeroesScoreboardRoute: AnalyticsHeroesScoreboardRoute,
  AnalyticsHeroesIndexRoute: AnalyticsHeroesIndexRoute,
}

const AnalyticsHeroesRouteWithChildren = AnalyticsHeroesRoute._addFileChildren(
  AnalyticsHeroesRouteChildren,
)

interface AnalyticsItemsRouteChildren {
  AnalyticsItemsItemNameRoute: typeof AnalyticsItemsItemNameRoute
  AnalyticsItemsBuildFlowRoute: typeof AnalyticsItemsBuildFlowRoute
  AnalyticsItemsCombosRoute: typeof AnalyticsItemsCombosRoute
  AnalyticsItemsItemPurchaseAnalysisRoute: typeof AnalyticsItemsItemPurchaseAnalysisRoute
  AnalyticsItemsIndexRoute: typeof AnalyticsItemsIndexRoute
}

const AnalyticsItemsRouteChildren: AnalyticsItemsRouteChildren = {
  AnalyticsItemsItemNameRoute: AnalyticsItemsItemNameRoute,
  AnalyticsItemsBuildFlowRoute: AnalyticsItemsBuildFlowRoute,
  AnalyticsItemsCombosRoute: AnalyticsItemsCombosRoute,
  AnalyticsItemsItemPurchaseAnalysisRoute:
    AnalyticsItemsItemPurchaseAnalysisRoute,
  AnalyticsItemsIndexRoute: AnalyticsItemsIndexRoute,
}

const AnalyticsItemsRouteWithChildren = AnalyticsItemsRoute._addFileChildren(
  AnalyticsItemsRouteChildren,
)

interface AnalyticsPlayersRouteChildren {
  AnalyticsPlayersStatsMetricsRoute: typeof AnalyticsPlayersStatsMetricsRoute
  AnalyticsPlayersIndexRoute: typeof AnalyticsPlayersIndexRoute
}

const AnalyticsPlayersRouteChildren: AnalyticsPlayersRouteChildren = {
  AnalyticsPlayersStatsMetricsRoute: AnalyticsPlayersStatsMetricsRoute,
  AnalyticsPlayersIndexRoute: AnalyticsPlayersIndexRoute,
}

const AnalyticsPlayersRouteWithChildren =
  AnalyticsPlayersRoute._addFileChildren(AnalyticsPlayersRouteChildren)

interface GamesDeadlockdleRouteChildren {
  GamesDeadlockdleGuessAbilityRoute: typeof GamesDeadlockdleGuessAbilityRoute
  GamesDeadlockdleGuessHeroRoute: typeof GamesDeadlockdleGuessHeroRoute
  GamesDeadlockdleGuessItemRoute: typeof GamesDeadlockdleGuessItemRoute
  GamesDeadlockdleGuessSoundRoute: typeof GamesDeadlockdleGuessSoundRoute
  GamesDeadlockdleItemStatsRoute: typeof GamesDeadlockdleItemStatsRoute
  GamesDeadlockdleTriviaRoute: typeof GamesDeadlockdleTriviaRoute
  GamesDeadlockdleIndexRoute: typeof GamesDeadlockdleIndexRoute
}

const GamesDeadlockdleRouteChildren: GamesDeadlockdleRouteChildren = {
  GamesDeadlockdleGuessAbilityRoute: GamesDeadlockdleGuessAbilityRoute,
  GamesDeadlockdleGuessHeroRoute: GamesDeadlockdleGuessHeroRoute,
  GamesDeadlockdleGuessItemRoute: GamesDeadlockdleGuessItemRoute,
  GamesDeadlockdleGuessSoundRoute: GamesDeadlockdleGuessSoundRoute,
  GamesDeadlockdleItemStatsRoute: GamesDeadlockdleItemStatsRoute,
  GamesDeadlockdleTriviaRoute: GamesDeadlockdleTriviaRoute,
  GamesDeadlockdleIndexRoute: GamesDeadlockdleIndexRoute,
}

const GamesDeadlockdleRouteWithChildren =
  GamesDeadlockdleRoute._addFileChildren(GamesDeadlockdleRouteChildren)

interface GamesFlashcardsRouteChildren {
  GamesFlashcardsHeroesRoute: typeof GamesFlashcardsHeroesRoute
  GamesFlashcardsItemEffectsRoute: typeof GamesFlashcardsItemEffectsRoute
  GamesFlashcardsItemUpgradesRoute: typeof GamesFlashcardsItemUpgradesRoute
  GamesFlashcardsItemsRoute: typeof GamesFlashcardsItemsRoute
  GamesFlashcardsIndexRoute: typeof GamesFlashcardsIndexRoute
}

const GamesFlashcardsRouteChildren: GamesFlashcardsRouteChildren = {
  GamesFlashcardsHeroesRoute: GamesFlashcardsHeroesRoute,
  GamesFlashcardsItemEffectsRoute: GamesFlashcardsItemEffectsRoute,
  GamesFlashcardsItemUpgradesRoute: GamesFlashcardsItemUpgradesRoute,
  GamesFlashcardsItemsRoute: GamesFlashcardsItemsRoute,
  GamesFlashcardsIndexRoute: GamesFlashcardsIndexRoute,
}

const GamesFlashcardsRouteWithChildren = GamesFlashcardsRoute._addFileChildren(
  GamesFlashcardsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbilitiesRoute: AbilitiesRoute,
  BadgeDistributionRoute: BadgeDistributionRoute,
  DataDumpsRoute: DataDumpsRoute,
  DataPrivacyRoute: DataPrivacyRoute,
  DeadlockdleRoute: DeadlockdleRouteWithChildren,
  DeadlockstatsPrivacyRoute: DeadlockstatsPrivacyRoute,
  FlashcardsRoute: FlashcardsRouteWithChildren,
  GamesRoute: GamesRoute,
  HeatmapRoute: HeatmapRoute,
  HeroesRoute: HeroesRouteWithChildren,
  IngestCacheRoute: IngestCacheRoute,
  ItemsRoute: ItemsRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  PatronRoute: PatronRoute,
  PlayersRoute: PlayersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Sitemap_indexDotxmlRoute: Sitemap_indexDotxmlRoute,
  TeamBuilderRoute: TeamBuilderRoute,
  TrackerRoute: TrackerRoute,
  AnalyticsAbilitiesRoute: AnalyticsAbilitiesRoute,
  AnalyticsGamesRoute: AnalyticsGamesRouteWithChildren,
  AnalyticsHeroesRoute: AnalyticsHeroesRouteWithChildren,
  AnalyticsItemsRoute: AnalyticsItemsRouteWithChildren,
  AnalyticsPlayersRoute: AnalyticsPlayersRouteWithChildren,
  AnalyticsTeamBuilderRoute: AnalyticsTeamBuilderRoute,
  BlogSlugRoute: BlogSlugRoute,
  CommunityBadgeDistributionRoute: CommunityBadgeDistributionRoute,
  CommunityHeatmapRoute: CommunityHeatmapRoute,
  CommunityLeaderboardRoute: CommunityLeaderboardRoute,
  DevDesignSystemRoute: DevDesignSystemRoute,
  GamesDeadlockdleRoute: GamesDeadlockdleRouteWithChildren,
  GamesFlashcardsRoute: GamesFlashcardsRouteWithChildren,
  PlayersAccountIdRoute: PlayersAccountIdRoute,
  TrackerDemoRoute: TrackerDemoRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  StreamkitIndexRoute: StreamkitIndexRoute,
  AuthPatreonCallbackRoute: AuthPatreonCallbackRoute,
  TrackerPlayersAccountIdRoute: TrackerPlayersAccountIdRoute,
  TrackerPlayersIndexRoute: TrackerPlayersIndexRoute,
  StreamkitWidgetsRegionAccountIdWidgetTypeRoute:
    StreamkitWidgetsRegionAccountIdWidgetTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
