name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: Fmt, Lint & Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm fmt && git diff --exit-code

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
