use bytes::Bytes;
use cached::macros::cached;
use object_store::aws::AmazonS3;
use strum::IntoStaticStr;

use crate::services::assets::versions::store::{VersionStoreError, fetch_zst};

/// Asset folders that have a published `index.json.zst` file-tree.
#[derive(Debug, Clone, Copy, IntoStaticStr)]
#[strum(serialize_all = "lowercase")]
pub(crate) enum IndexFolder {
    Images,
    Icons,
    Sounds,
    Fonts,
}

/// Fetch the cached JSON file-tree index for `folder`.
// `result_fallback`: the index is regenerated by the asset pipeline, not by us, so
// the last good copy is always a valid answer when R2 is unreachable.
#[cached(
    ttl_secs = 3600,
    convert = r#"{ <&str>::from(folder) }"#,
    key = "&'static str",
    result_fallback = true
)]
pub(crate) async fn fetch_index(
    r2: &AmazonS3,
    folder: IndexFolder,
) -> Result<Bytes, VersionStoreError> {
    let folder = <&str>::from(folder);
    fetch_zst(r2, &format!("assets-api-res/{folder}/index.json.zst")).await
}
