[advisories]
ignore = [
    "RUSTSEC-2023-0071", # rsa: potential key recovery through timing sidechannels
]
informational_warnings = ["unmaintained"] # warn for categories of informational advisories
severity_threshold = "low" # CVSS severity ("none", "low", "medium", "high", "critical")
