import type {
  AbilityOrderStatsGameModeEnum,
  AnalyticsApiBadgeDistributionRequest,
  AnalyticsApiKillDeathStatsRequest,
  GameStatsBucketEnum,
} from "deadlock_api_client";
import type { GameMode } from "~/components/selectors/GameModeSelector";
import { patronQueryKeys } from "./patron-queries";

type Nullable<T> = T | null | undefined;

export const queryKeys = {
  assets: {
    heroes: () => ["assets-heroes"] as const,
    itemUpgrades: () => ["assets-items-upgrades"] as const,
    abilities: () => ["assets-items-abilities"] as const,
    ranks: () => ["assets-ranks"] as const,
    hero: (heroId: number) => ["assets-hero", heroId] as const,
  },
  analytics: {
    heroStats: (
      minRankId: Nullable<number>,
      maxRankId: Nullable<number>,
      minDateTimestamp: Nullable<number>,
      maxDateTimestamp: Nullable<number>,
      minHeroMatches: Nullable<number>,
      minHeroMatchesTotal?: Nullable<number>,
      gameMode?: Nullable<GameMode>,
    ) =>
      [
        "api-hero-stats",
        minRankId,
        maxRankId,
        minDateTimestamp,
        maxDateTimestamp,
        minHeroMatches,
        minHeroMatchesTotal,
        gameMode,
      ] as const,
    heroSynergyStats: (
      minRankId: Nullable<number>,
      maxRankId: Nullable<number>,
      minDateTimestamp: Nullable<number>,
      maxDateTimestamp: Nullable<number>,
      sameLaneFilter: Nullable<boolean>,
      samePartyFilter: Nullable<boolean>,
      minMatches: Nullable<number>,
      gameMode?: Nullable<GameMode>,
    ) =>
      [
        "api-hero-synergy-stats",
        minRankId,
        maxRankId,
        minDateTimestamp,
        maxDateTimestamp,
        sameLaneFilter,
        samePartyFilter,
        minMatches,
        gameMode,
      ] as const,
    heroCounterStats: (
      minRankId: Nullable<number>,
      maxRankId: Nullable<number>,
      minDateTimestamp: Nullable<number>,
      maxDateTimestamp: Nullable<number>,
      sameLaneFilter: Nullable<boolean>,
      minMatches: Nullable<number>,
      gameMode?: Nullable<GameMode>,
    ) =>
      [
        "api-hero-counter-stats",
        minRankId,
        maxRankId,
        minDateTimestamp,
        maxDateTimestamp,
        sameLaneFilter,
        minMatches,
        gameMode,
      ] as const,
    heroCombStats: (
      minRankId: Nullable<number>,
      maxRankId: Nullable<number>,
      minDateTimestamp: Nullable<number>,
      maxDateTimestamp: Nullable<number>,
      combSize: Nullable<number>,
      minHeroMatches: Nullable<number>,
      gameMode?: Nullable<GameMode>,
    ) =>
      [
        "api-hero-comb-stats",
        minRankId,
        maxRankId,
        minDateTimestamp,
        maxDateTimestamp,
        combSize,
        minHeroMatches,
        gameMode,
      ] as const,
    heroStatsByRank: (
      minDateTimestamp: Nullable<number>,
      maxDateTimestamp: Nullable<number>,
      minHeroMatches: Nullable<number>,
      minHeroMatchesTotal: Nullable<number>,
      gameMode?: Nullable<GameMode>,
    ) =>
      [
        "api-hero-stats-by-rank",
        minDateTimestamp,
        maxDateTimestamp,
        minHeroMatches,
        minHeroMatchesTotal,
        gameMode,
      ] as const,
    heroStatsOverTime: (
      minRankId: Nullable<number>,
      maxRankId: Nullable<number>,
      minDateTimestamp: Nullable<number>,
      maxDateTimestamp: Nullable<number>,
      heroTimeInterval: Nullable<string>,
      minHeroMatches: Nullable<number>,
      minHeroMatchesTotal: Nullable<number>,
      gameMode?: Nullable<GameMode>,
    ) =>
      [
        "api-hero-stats-over-time",
        minRankId,
        maxRankId,
        minDateTimestamp,
        maxDateTimestamp,
        heroTimeInterval,
        minHeroMatches,
        minHeroMatchesTotal,
        gameMode,
      ] as const,
    heroStatsByDuration: (
      minDurationS: number,
      maxDurationS: number,
      minRankId: Nullable<number>,
      maxRankId: Nullable<number>,
      minDateTimestamp: Nullable<number>,
      maxDateTimestamp: Nullable<number>,
      minHeroMatches: Nullable<number>,
      minHeroMatchesTotal: Nullable<number>,
      gameMode?: Nullable<GameMode>,
    ) =>
      [
        "api-hero-stats-by-duration",
        minDurationS,
        maxDurationS,
        minRankId,
        maxRankId,
        minDateTimestamp,
        maxDateTimestamp,
        minHeroMatches,
        minHeroMatchesTotal,
        gameMode,
      ] as const,
    heroStatsByExperience: (
      minExperience: number,
      maxExperience: number,
      minRankId: Nullable<number>,
      maxRankId: Nullable<number>,
      minDateTimestamp: Nullable<number>,
      maxDateTimestamp: Nullable<number>,
      minHeroMatches: Nullable<number>,
      gameMode?: Nullable<GameMode>,
    ) =>
      [
        "api-hero-stats-by-experience",
        minExperience,
        maxExperience,
        minRankId,
        maxRankId,
        minDateTimestamp,
        maxDateTimestamp,
        minHeroMatches,
        gameMode,
      ] as const,
    // itemStats has inconsistent call sites (item-stats-query passes bucket/include/exclude,
    // ItemStatsTable passes minBoughtAtS/maxBoughtAtS directly). Kept as rest params until
    // call sites are unified to use itemStatsQueryOptions exclusively.
    itemStats: (...params: unknown[]) => ["api-item-stats", ...params] as const,
    gameStats: (
      bucket: Nullable<GameStatsBucketEnum>,
      gameMode: Nullable<GameMode>,
      minUnixTimestamp: Nullable<number>,
      maxUnixTimestamp: Nullable<number>,
      minDurationS: Nullable<number>,
      maxDurationS: Nullable<number>,
      minAverageBadge: Nullable<number>,
      maxAverageBadge: Nullable<number>,
    ) =>
      [
        "api-game-stats",
        bucket,
        gameMode,
        minUnixTimestamp,
        maxUnixTimestamp,
        minDurationS,
        maxDurationS,
        minAverageBadge,
        maxAverageBadge,
      ] as const,
    abilityOrderStats: (
      heroId: number,
      minRankId: Nullable<number>,
      maxRankId: Nullable<number>,
      minDateTimestamp: Nullable<number>,
      maxDateTimestamp: Nullable<number>,
      minMatches: Nullable<number>,
      gameMode: Nullable<AbilityOrderStatsGameModeEnum>,
      includeItemIds: Nullable<number[]>,
      excludeItemIds: Nullable<number[]>,
    ) =>
      [
        "api-ability-order-stats",
        heroId,
        minRankId,
        maxRankId,
        minDateTimestamp,
        maxDateTimestamp,
        minMatches,
        gameMode,
        includeItemIds,
        excludeItemIds,
      ] as const,
    killDeathStats: (params: AnalyticsApiKillDeathStatsRequest) => ["killDeathStats", params] as const,
    badgeDistribution: (filter: AnalyticsApiBadgeDistributionRequest) => ["badgeDistribution", filter] as const,
    playerScoreboard: (
      sortBy: string,
      sortDirection: string,
      gameMode: Nullable<GameMode>,
      heroId: Nullable<number>,
      minMatches: Nullable<number>,
      minRankId: Nullable<number>,
      maxRankId: Nullable<number>,
      startDate: Nullable<number>,
      endDate: Nullable<number>,
    ) =>
      [
        "playerScoreboard",
        sortBy,
        sortDirection,
        gameMode,
        heroId,
        minMatches,
        minRankId,
        maxRankId,
        startDate,
        endDate,
      ] as const,
    topBuilds: (
      hero: Nullable<number>,
      includeItems: number[],
      excludeItems: number[],
      minRankId: Nullable<number>,
      maxRankId: Nullable<number>,
      minDateTimestamp: Nullable<number>,
      maxDateTimestamp: Nullable<number>,
      gameMode?: Nullable<GameMode>,
    ) =>
      [
        "top-builds",
        hero,
        includeItems,
        excludeItems,
        minRankId,
        maxRankId,
        minDateTimestamp,
        maxDateTimestamp,
        gameMode,
      ] as const,
  },
  leaderboard: {
    data: (region: string, heroId?: number | null) => ["leaderboardData", region, heroId] as const,
    ranks: () => ["ranks"] as const,
  },
  steam: {
    profiles: (batch: number[]) => ["steamProfiles", batch] as const,
    profile: (accountId: number | undefined) => ["steam-profile", accountId] as const,
    name: (region: string, steamId: string) => ["steamName", region, steamId] as const,
  },
  streamkit: {
    version: (widgetType: string | undefined) => ["version", widgetType] as const,
    stats: (region: string, accountId: string, ...rest: unknown[]) => ["stats", region, accountId, ...rest] as const,
    heroes: () => ["heroes"] as const,
    matchHistory: (accountId: string) => ["match-history", accountId] as const,
    availableVariables: () => ["available-variables"] as const,
    preview: (url: string) => ["preview", url] as const,
  },
  map: () => ["map"] as const,
  patron: patronQueryKeys,
} as const;
