[workspace]
members = ["salt-scraper", "hltv-scraper", "ingest-worker", "matchdata-downloader", "active-matches-scraper", "builds-fetcher", "common", "history-fetcher", "steam-profile-fetcher", "update-assets-tables", "demo-analyzer", "friends-rank-fetcher"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.104"
async-compression = "0.4.43"
base64 = "0.23.1"
cached = "3.1"
clap = { version = "4.6.6", features = ["derive", "env"] }
clickhouse = "0.15.2"
common = { version = "0.1.0", path = "common" }
fred = { version = "10.1.0", features = ["i-hexpire"] }
futures = "0.3.34"
itertools = "0.15.0"
metrics = "0.24.6"
object_store = { version = "0.14.1", features = ["aws"] }
opentelemetry = { version = "0.32", features = ["logs", "trace"] }
opentelemetry_sdk = { version = "0.32", features = ["logs", "trace"] }
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic", "logs", "trace"] }
opentelemetry-appender-tracing = { version = "0.32", features = ["experimental_metadata_attributes"] }
prost = "0.14.4"
rand = "0.10.2"
reqwest = "0.13.4"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_repr = "0.1.21"
sqlx = "0.9.0"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
tokio-util = "0.7.19"
tracing = "0.1.44"
tracing-opentelemetry = "0.33"
tryhard = "0.5.2"
valveprotos = { git = "https://github.com/deadlock-api/valveprotos-rs.git", rev = "4f4a3cb1b0c6f19af59a722acb79ecccd01f61f6" }
haste = { git = "https://github.com/deadlock-api/haste.git", rev = "95b6104fc41837cc4c5495f4a4de8afc531b9195", features = ["async"] }
