packages:
  - website

allowBuilds:
  '@tailwindcss/oxide': true
  assets_deadlock_api_client: true
  core-js: true
  deadlock_api_client: true
  esbuild: true
  protobufjs: true
  sharp: set this to true or false
  unrs-resolver: true
  workerd: set this to true or false

minimumReleaseAge: 1440

overrides:
  typescript: ^6.0.3
