import {
  Activity,
  ArrowRight,
  Bot,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleDot,
  Clock,
  Coins,
  Crosshair,
  Eye,
  Flag,
  Flame,
  Footprints,
  Gauge,
  Handshake,
  Hourglass,
  Info,
  type LucideIcon,
  Lightbulb,
  Map,
  MapPin,
  MessageCircle,
  Pause,
  Play,
  Route,
  Shield,
  Skull,
  Sparkles,
  Star,
  Swords,
  Target,
  Timer,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Users,
  Zap,
} from "lucide-react";
import { type CSSProperties, createElement } from "react";

// The agent references icons by short kebab/snake names; map them to lucide
// components. Unknown names fall back to a neutral dot so a typo never breaks
// a render. Aliases keep the agent's vocabulary forgiving.
const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  "arrow-right": ArrowRight,
  bot: Bot,
  "chevron-right": ChevronRight,
  alert: CircleAlert,
  "circle-alert": CircleAlert,
  check: CircleCheck,
  "circle-check": CircleCheck,
  dot: CircleDot,
  clock: Clock,
  time: Clock,
  coins: Coins,
  souls: Coins,
  gold: Coins,
  crosshair: Crosshair,
  eye: Eye,
  vision: Eye,
  camera: Eye,
  flag: Flag,
  objective: Flag,
  flame: Flame,
  fire: Flame,
  footprints: Footprints,
  rotation: Route,
  gauge: Gauge,
  handshake: Handshake,
  assist: Handshake,
  hourglass: Hourglass,
  info: Info,
  lightbulb: Lightbulb,
  tip: Lightbulb,
  idea: Lightbulb,
  map: Map,
  "map-pin": MapPin,
  pin: MapPin,
  "message-circle": MessageCircle,
  message: MessageCircle,
  chat: MessageCircle,
  ask: MessageCircle,
  question: MessageCircle,
  pause: Pause,
  play: Play,
  route: Route,
  shield: Shield,
  defense: Shield,
  skull: Skull,
  death: Skull,
  sparkles: Sparkles,
  star: Star,
  swords: Swords,
  fight: Swords,
  kill: Swords,
  target: Target,
  timer: Timer,
  "trending-up": TrendingUp,
  up: TrendingUp,
  "trending-down": TrendingDown,
  down: TrendingDown,
  warning: TriangleAlert,
  "triangle-alert": TriangleAlert,
  trophy: Trophy,
  win: Trophy,
  users: Users,
  team: Users,
  zap: Zap,
  ability: Zap,
};

export function iconByName(name?: string | null): LucideIcon {
  if (!name) return CircleDot;
  return ICONS[name] ?? ICONS[name.toLowerCase().replace(/_/g, "-")] ?? CircleDot;
}

export function CoachIcon({
  name,
  className,
  style,
}: {
  name?: string | null;
  className?: string;
  style?: CSSProperties;
}) {
  return createElement(iconByName(name), { className, style });
}
