use std::fs;
use std::path::PathBuf;

use heck::ToUpperCamelCase;
use prost_reflect::{DescriptorPool, FieldDescriptor, Kind, MessageDescriptor};

fn main() {
    println!("cargo::rerun-if-env-changed=DEP_VALVEPROTOS_DESCRIPTORS");

    let descriptors_path = match std::env::var("DEP_VALVEPROTOS_DESCRIPTORS") {
        Ok(path) => path,
        Err(_) => {
            eprintln!("DEP_VALVEPROTOS_DESCRIPTORS not set, skipping event codegen");
            return;
        }
    };

    println!("cargo::rerun-if-changed={descriptors_path}");

    let descriptors = fs::read(&descriptors_path).expect("failed to read descriptors.bin");
    let pool = DescriptorPool::decode(&descriptors[..]).expect("failed to decode descriptors");

    let generated = generate_events_code(&pool);

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("events_generated.rs");
    fs::write(&out_path, &generated).expect("failed to write generated code");
}

fn generate_events_code(pool: &DescriptorPool) -> String {
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs - DO NOT EDIT\n\n");

    let event_mappings = extract_event_mappings(pool);

    generate_event_type_enum(&mut code, &event_mappings);
    generate_decoded_event_enum(&mut code, &event_mappings);
    generate_decode_function(&mut code, &event_mappings);
    generate_event_schema(&mut code, pool, &event_mappings);
    generate_append_impl(&mut code, pool, &event_mappings);

    code
}

#[derive(Debug, Clone)]
struct EventMapping {
    message_id: i32,
    enum_variant_name: String,
    message_name: String,
    rust_type_path: String,
    table_name: String,
}

fn extract_event_mappings(pool: &DescriptorPool) -> Vec<EventMapping> {
    let enum_desc = pool
        .get_enum_by_name("CitadelUserMessageIds")
        .expect("CitadelUserMessageIds enum not found");

    let mut mappings = Vec::new();

    for value in enum_desc.values() {
        let enum_name = value.name();
        let message_id = value.number();

        if !enum_name.starts_with("k_EUserMsg_") {
            continue;
        }

        let short_name = enum_name.strip_prefix("k_EUserMsg_").unwrap();

        let message_name = find_message_name_for_event(pool, short_name);
        if message_name.is_none() {
            eprintln!("Warning: No message found for {enum_name} (id={message_id})");
            continue;
        }

        let message_name = message_name.unwrap();
        let rust_type_path = format!(
            "valveprotos::deadlock::{}",
            proto_message_name_to_rust_type(&message_name)
        );

        mappings.push(EventMapping {
            message_id,
            enum_variant_name: short_name.to_string(),
            message_name: message_name.clone(),
            rust_type_path,
            table_name: format!("{short_name}Event"),
        });
    }

    mappings.sort_by_key(|m| m.message_id);
    mappings
}

fn find_message_name_for_event(pool: &DescriptorPool, short_name: &str) -> Option<String> {
    let candidates = [
        format!("CCitadelUserMsg_{short_name}"),
        format!("CCitadelUserMessage_{short_name}"),
        format!("CCitadelUserMsg{short_name}"),
    ];

    for candidate in &candidates {
        if pool.get_message_by_name(candidate).is_some() {
            return Some(candidate.clone());
        }
    }

    None
}

fn generate_event_type_enum(code: &mut String, mappings: &[EventMapping]) {
    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    code.push_str("pub enum EventType {\n");
    for mapping in mappings {
        code.push_str(&format!(
            "    {} = {},\n",
            mapping.enum_variant_name, mapping.message_id
        ));
    }
    code.push_str("}\n\n");

    code.push_str("impl EventType {\n");
    code.push_str("    pub fn table_name(&self) -> &'static str {\n");
    code.push_str("        match self {\n");
    for mapping in mappings {
        code.push_str(&format!(
            "            EventType::{} => \"{}\",\n",
            mapping.enum_variant_name, mapping.table_name
        ));
    }
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    pub fn message_id(&self) -> u32 {\n");
    code.push_str("        match self {\n");
    for mapping in mappings {
        code.push_str(&format!(
            "            EventType::{} => {},\n",
            mapping.enum_variant_name, mapping.message_id
        ));
    }
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    pub fn all() -> &'static [EventType] {\n");
    code.push_str("        &[\n");
    for mapping in mappings {
        code.push_str(&format!(
            "            EventType::{},\n",
            mapping.enum_variant_name
        ));
    }
    code.push_str("        ]\n");
    code.push_str("    }\n");

    code.push_str("}\n\n");
}

fn generate_decoded_event_enum(code: &mut String, mappings: &[EventMapping]) {
    code.push_str("#[derive(Debug, Clone)]\n");
    code.push_str("pub enum DecodedEvent {\n");
    for mapping in mappings {
        code.push_str(&format!(
            "    {}({}),\n",
            mapping.enum_variant_name, mapping.rust_type_path
        ));
    }
    code.push_str("}\n\n");
}

fn generate_decode_function(code: &mut String, mappings: &[EventMapping]) {
    code.push_str("pub fn decode_event(message_id: u32, data: &[u8]) -> Option<DecodedEvent> {\n");
    code.push_str("    use prost::Message;\n");
    code.push_str("    match message_id {\n");
    for mapping in mappings {
        code.push_str(&format!(
            "        {} => {}::decode(data).ok().map(DecodedEvent::{}),\n",
            mapping.message_id, mapping.rust_type_path, mapping.enum_variant_name
        ));
    }
    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
}

fn generate_event_schema(code: &mut String, pool: &DescriptorPool, mappings: &[EventMapping]) {
    code.push_str("pub fn event_schema(table_name: &str) -> Option<std::sync::Arc<datafusion::arrow::datatypes::Schema>> {\n");
    code.push_str("    use datafusion::arrow::datatypes::{DataType, Field, Fields, Schema};\n");
    code.push_str("    use std::sync::Arc;\n\n");
    code.push_str("    match table_name {\n");

    for mapping in mappings {
        let msg_desc = pool.get_message_by_name(&mapping.message_name);
        if let Some(msg_desc) = msg_desc {
            code.push_str(&format!(
                "        \"{}\" => Some(Arc::new(Schema::new(vec![\n",
                mapping.table_name
            ));
            code.push_str("            Field::new(\"tick\", DataType::Int32, false),\n");

            for field in msg_desc.fields() {
                let field_name = field.name();
                let arrow_type = field_to_arrow_type(&field);
                code.push_str(&format!(
                    "            Field::new(\"{field_name}\", {arrow_type}, true),\n"
                ));
            }

            code.push_str("        ]))),\n");
        }
    }

    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");
}

fn field_to_arrow_type(field: &FieldDescriptor) -> String {
    let kind = field.kind();

    if field.is_list() {
        let inner_type = scalar_or_message_arrow_type(&kind);
        return format!("DataType::List(Arc::new(Field::new(\"item\", {inner_type}, true)))");
    }

    scalar_or_message_arrow_type(&kind)
}

fn scalar_or_message_arrow_type(kind: &Kind) -> String {
    match kind {
        Kind::Int32 | Kind::Sint32 | Kind::Sfixed32 | Kind::Enum(_) => {
            "DataType::Int32".to_string()
        }
        Kind::Int64 | Kind::Sint64 | Kind::Sfixed64 => "DataType::Int64".to_string(),
        Kind::Uint32 | Kind::Fixed32 => "DataType::UInt32".to_string(),
        Kind::Uint64 | Kind::Fixed64 => "DataType::UInt64".to_string(),
        Kind::Float => "DataType::Float32".to_string(),
        Kind::Double => "DataType::Float64".to_string(),
        Kind::Bool => "DataType::Boolean".to_string(),
        Kind::String => "DataType::Utf8".to_string(),
        Kind::Bytes => "DataType::Binary".to_string(),
        Kind::Message(nested_desc) => {
            let mut fields = Vec::new();
            for nested_field in nested_desc.fields() {
                let nested_name = nested_field.name();
                let nested_type = field_to_arrow_type(&nested_field);
                fields.push(format!(
                    "Field::new(\"{nested_name}\", {nested_type}, true)"
                ));
            }
            format!(
                "DataType::Struct(Fields::from(vec![{}]))",
                fields.join(", ")
            )
        }
    }
}

fn generate_append_impl(code: &mut String, pool: &DescriptorPool, mappings: &[EventMapping]) {
    code.push_str("pub fn append_event_to_builders(\n");
    code.push_str("    event: &DecodedEvent,\n");
    code.push_str("    builders: &mut [Box<dyn datafusion::arrow::array::ArrayBuilder>],\n");
    code.push_str(") {\n");
    code.push_str("    use datafusion::arrow::array::*;\n");
    code.push_str("    match event {\n");

    for mapping in mappings {
        let msg_desc = pool.get_message_by_name(&mapping.message_name);
        if let Some(msg_desc) = msg_desc {
            code.push_str(&format!(
                "        DecodedEvent::{}(msg) => {{\n",
                mapping.enum_variant_name
            ));
            generate_field_appends(code, &msg_desc);
            code.push_str("        }\n");
        }
    }

    code.push_str("    }\n");
    code.push_str("}\n\n");
}

fn generate_field_appends(code: &mut String, msg_desc: &MessageDescriptor) {
    for (i, field) in msg_desc.fields().enumerate() {
        let field_name = field.name();
        let rust_field_name = proto_field_to_rust_name(field_name);

        let ctx = GenContext {
            builder_expr: format!("builders[{i}].as_any_mut().downcast_mut"),
            source_expr: "msg".to_string(),
            depth: 0,
        };

        let append_code = generate_field_append(&field, &rust_field_name, &ctx);
        code.push_str(&format!("            {append_code}\n"));
    }
}

fn proto_field_to_rust_name(proto_name: &str) -> String {
    const RUST_KEYWORDS: &[&str] = &[
        "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
        "mut", "override", "pub", "ref", "return", "self", "Self", "static", "struct", "super",
        "trait", "true", "type", "unsafe", "use", "where", "while", "abstract", "become", "box",
        "do", "final", "macro", "offsetof", "priv", "proc", "pure", "sizeof", "typeof", "unsized",
        "virtual", "yield", "try",
    ];

    if RUST_KEYWORDS.contains(&proto_name) {
        format!("r#{proto_name}")
    } else {
        proto_name.to_string()
    }
}

fn proto_message_name_to_rust_type(proto_name: &str) -> String {
    proto_name.to_upper_camel_case()
}

struct GenContext {
    builder_expr: String,
    source_expr: String,
    depth: usize,
}

impl GenContext {
    fn var_name(&self, base: &str) -> String {
        if self.depth == 0 {
            base.to_string()
        } else {
            format!("{}_{}", base, self.depth)
        }
    }
}

fn scalar_builder_type(kind: &Kind) -> &'static str {
    match kind {
        Kind::Int32 | Kind::Sint32 | Kind::Sfixed32 | Kind::Enum(_) => "Int32Builder",
        Kind::Int64 | Kind::Sint64 | Kind::Sfixed64 => "Int64Builder",
        Kind::Uint32 | Kind::Fixed32 => "UInt32Builder",
        Kind::Uint64 | Kind::Fixed64 => "UInt64Builder",
        Kind::Float => "Float32Builder",
        Kind::Double => "Float64Builder",
        Kind::Bool => "BooleanBuilder",
        Kind::String => "StringBuilder",
        Kind::Bytes => "BinaryBuilder",
        Kind::Message(_) => "StructBuilder",
    }
}

fn list_builder_type(kind: &Kind) -> String {
    format!("ListBuilder<{}>", scalar_builder_type(kind))
}

fn generate_field_append(
    field: &FieldDescriptor,
    rust_field_name: &str,
    ctx: &GenContext,
) -> String {
    let kind = field.kind();

    if field.is_list() {
        return generate_list_append(field, rust_field_name, ctx);
    }

    if let Kind::Message(nested_desc) = &kind {
        return generate_message_append(nested_desc, rust_field_name, ctx);
    }

    generate_scalar_append(&kind, rust_field_name, ctx)
}

fn generate_scalar_append(kind: &Kind, rust_field_name: &str, ctx: &GenContext) -> String {
    let builder_type = scalar_builder_type(kind);

    let value_expr = match kind {
        Kind::Enum(_) => format!("{}.{}.map(|v| v as i32)", ctx.source_expr, rust_field_name),
        Kind::String => format!("{}.{}.as_deref()", ctx.source_expr, rust_field_name),
        Kind::Bytes => format!("{}.{}.as_deref()", ctx.source_expr, rust_field_name),
        _ => format!("{}.{}", ctx.source_expr, rust_field_name),
    };

    if ctx.depth == 0 {
        format!(
            "{}::<{}>().unwrap().append_option({});",
            ctx.builder_expr, builder_type, value_expr
        )
    } else {
        format!("{}.append_option({});", ctx.builder_expr, value_expr)
    }
}

// child_accessor is ".values()" when `bvar` is a ListBuilder (children live behind
// .values()) or "" when `bvar` is a StructBuilder (children reached directly).
fn emit_child_field(
    code: &mut String,
    bvar: &str,
    child_accessor: &str,
    src: &str,
    parent_depth: usize,
    child_idx: usize,
    child_field: &FieldDescriptor,
) {
    let child_name = child_field.name();
    let child_rust_name = proto_field_to_rust_name(child_name);
    let child_kind = child_field.kind();

    let child_builder_type = if child_field.is_list() {
        list_builder_type(&child_kind)
    } else {
        scalar_builder_type(&child_kind).to_string()
    };

    let child_ctx = GenContext {
        builder_expr: format!(
            "{bvar}{child_accessor}.field_builder::<{child_builder_type}>({child_idx})"
        ),
        source_expr: src.to_string(),
        depth: parent_depth + 1,
    };

    if child_field.is_list() {
        code.push_str(&generate_list_append(
            child_field,
            &child_rust_name,
            &child_ctx,
        ));
    } else if let Kind::Message(nested) = &child_kind {
        code.push_str(&generate_message_append(
            nested,
            &child_rust_name,
            &child_ctx,
        ));
    } else {
        code.push_str(&format!(
            "{}{}.field_builder::<{}>({}).unwrap().append_option({});",
            bvar,
            child_accessor,
            scalar_builder_type(&child_kind),
            child_idx,
            generate_value_expr(&child_kind, src, &child_rust_name)
        ));
    }
}

fn emit_child_field_null(
    code: &mut String,
    bvar: &str,
    child_accessor: &str,
    child_idx: usize,
    child_field: &FieldDescriptor,
) {
    let child_kind = child_field.kind();
    if child_field.is_list() {
        code.push_str(&format!(
            "{}{}.field_builder::<{}>({}).unwrap().append(false);",
            bvar,
            child_accessor,
            list_builder_type(&child_kind),
            child_idx
        ));
    } else if let Kind::Message(_) = &child_kind {
        code.push_str(&format!(
            "{bvar}{child_accessor}.field_builder::<StructBuilder>({child_idx}).unwrap().append(false);"
        ));
    } else {
        code.push_str(&format!(
            "{}{}.field_builder::<{}>({}).unwrap().append_null();",
            bvar,
            child_accessor,
            scalar_builder_type(&child_kind),
            child_idx
        ));
    }
}

fn generate_list_append(
    field: &FieldDescriptor,
    rust_field_name: &str,
    ctx: &GenContext,
) -> String {
    let kind = field.kind();
    let lb_var = ctx.var_name("lb");
    let item_var = ctx.var_name("item");

    let builder_type = list_builder_type(&kind);

    let get_builder = if ctx.depth == 0 {
        format!("{}::<{}>().unwrap()", ctx.builder_expr, builder_type)
    } else {
        format!("{}.unwrap()", ctx.builder_expr)
    };

    let mut code = format!("{{ let {lb_var} = {get_builder}; ");

    code.push_str(&format!(
        "for {} in &{}.{} {{ ",
        item_var, ctx.source_expr, rust_field_name
    ));

    match &kind {
        Kind::Message(nested_desc) => {
            for (child_idx, child_field) in nested_desc.fields().enumerate() {
                emit_child_field(
                    &mut code,
                    &lb_var,
                    ".values()",
                    &item_var,
                    ctx.depth,
                    child_idx,
                    &child_field,
                );
                code.push(' ');
            }
            code.push_str(&format!("{lb_var}.values().append(true); "));
        }
        _ => {
            let value_expr = match &kind {
                Kind::Enum(_) => format!("*{item_var} as i32"),
                Kind::String => item_var.to_string(),
                Kind::Bytes => item_var.to_string(),
                _ => format!("*{item_var}"),
            };
            code.push_str(&format!("{lb_var}.values().append_value({value_expr}); "));
        }
    }

    code.push_str("} ");
    code.push_str(&format!("{lb_var}.append(true); }}"));

    code
}

fn generate_value_expr(kind: &Kind, source: &str, field_name: &str) -> String {
    match kind {
        Kind::Enum(_) => format!("{source}.{field_name}.map(|v| v as i32)"),
        Kind::String => format!("{source}.{field_name}.as_deref()"),
        Kind::Bytes => format!("{source}.{field_name}.as_deref()"),
        _ => format!("{source}.{field_name}"),
    }
}

fn generate_message_append(
    nested_desc: &MessageDescriptor,
    rust_field_name: &str,
    ctx: &GenContext,
) -> String {
    let sb_var = ctx.var_name("sb");
    let nested_var = ctx.var_name("nested");

    let get_builder = if ctx.depth == 0 {
        format!("{}::<StructBuilder>().unwrap()", ctx.builder_expr)
    } else {
        format!("{}.unwrap()", ctx.builder_expr)
    };

    let mut code = format!("{{ let {sb_var} = {get_builder}; ");

    code.push_str(&format!(
        "if let Some(ref {}) = {}.{} {{ ",
        nested_var, ctx.source_expr, rust_field_name
    ));

    for (child_idx, child_field) in nested_desc.fields().enumerate() {
        emit_child_field(
            &mut code,
            &sb_var,
            "",
            &nested_var,
            ctx.depth,
            child_idx,
            &child_field,
        );
        code.push(' ');
    }

    code.push_str(&format!("{sb_var}.append(true); "));
    code.push_str("} else { ");

    for (child_idx, child_field) in nested_desc.fields().enumerate() {
        emit_child_field_null(&mut code, &sb_var, "", child_idx, &child_field);
        code.push(' ');
    }

    code.push_str(&format!("{sb_var}.append(false); "));
    code.push_str("} }");

    code
}
