name: Website CI

on:
  push:
    branches:
      - master
    paths:
      - 'website/**'
      - '.github/workflows/website-ci.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'website/**'
      - '.github/workflows/website-ci.yml'

jobs:
  ci:
    name: Fmt, Lint & Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: website

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: website/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm fmt && git diff --exit-code

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
